import { mkdirSync, writeFileSync } from 'node:fs'
import { lessons } from '../src/algorithms'

type Grade = 'A'|'B'|'C'|'D'
type Repair = 'S0'|'S1'|'S2'|'S3'

const reviewed: Record<string,{animation:Grade;codeSync:Grade;repair:Repair;note:string}> = {
  'binary-search': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete interval/midpoint trace; comparison frame can own the wrong primary code line.'},
  'bfs': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete queue/distances; some discovery events map to nearby control-flow lines.'},
  'dijkstra': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete heap/stale/relax trace; some relax events map to loop/header lines.'},
  'segment-tree': {animation:'B',codeSync:'B',repair:'S0',note:'Strong lifecycle; fix query-label/state inconsistency and exact code ownership.'},
  'prefix-xor': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete px/a/XOR evolution; generic 10-step expansion.'},
  'fenwick-tree': {animation:'C',codeSync:'C',repair:'S1',note:'Useful lowbit/path states exist but BIT values do not execute continuously.'},
  'kmp': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete pattern, i, j, pi evolution or fallback chain.'},
  'knapsack-01': {animation:'D',codeSync:'D',repair:'S2',note:'No real dp array mutation across items/capacities.'},
  'tarjan-scc': {animation:'C',codeSync:'C',repair:'S1',note:'Good disc/low/stack snapshots; generic expansion breaks continuous DFS execution.'},
  'digit-dp': {animation:'D',codeSync:'D',repair:'S2',note:'State dimensions are named but no concrete digit-state recursion is executed.'},
  'dinic': {animation:'D',codeSync:'D',repair:'S3',note:'Missing capacities, levels, blocking-flow paths and residual updates.'},
  'meet-in-the-middle': {animation:'D',codeSync:'D',repair:'S2',note:'20 code-position steps from 3 concepts; subset-sum lists never execute.'},
  'monotonic-stack': {animation:'C',codeSync:'C',repair:'S1',note:'Real stack snapshots exist but jump between examples without one continuous input.'},
  'topological-sort': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete indegree/queue exists; missing edge-by-edge decrements and pushes.'},
  'lca-binary-lifting': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete u/v/jump states; missing jump-table reasoning and continuous k scan.'},
  'lazy-segment-tree': {animation:'C',codeSync:'C',repair:'S1',note:'Covered intervals/tags known; 20 code steps spread across only a few semantic states.'},
  'longest-increasing-subsequence': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete tails snapshots exist but do not execute one sequence continuously.'},
  'aho-corasick': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete trie nodes, fail links, text cursor, fallback or reports.'},
  'min-cost-max-flow': {animation:'D',codeSync:'D',repair:'S3',note:'No concrete capacities/costs/path/bottleneck/reverse-edge/cumulative cost state.'},
  'extended-euclid': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete recursion or Bézout coefficient back-substitution.'},
  'rotating-calipers': {animation:'D',codeSync:'D',repair:'S2',note:'No polygon, antipodal pair, area comparison or pointer movement.'},
  'fft': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete coefficients, roots, butterfly values or transform stages.'},
  'linear-search': {animation:'A',codeSync:'A',repair:'S0',note:'Concrete index-by-index execution on one array; state and comparison line remain aligned.'},
  'sliding-window': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete l/r/sum evolution on one input; some add steps map to loop headers rather than the exact sum mutation.'},
  'dsu': {animation:'C',codeSync:'C',repair:'S1',note:'Parent/path-compression/merge snapshots exist, but generic expansion interrupts the actual find/unite sequence.'},
  'floyd-warshall': {animation:'C',codeSync:'C',repair:'S1',note:'One concrete B→E via C relaxation exists; full matrix evolution across k is missing.'},
  'heavy-light-decomposition': {animation:'C',codeSync:'C',repair:'S1',note:'Heavy/light edges and path segments exist, but chain jumps are not executed continuously.'},
  'persistent-segment-tree': {animation:'C',codeSync:'C',repair:'S1',note:'Version roots and copied path are meaningful; node copying and shared-subtree changes need stepwise execution.'},
  'sparse-table': {animation:'C',codeSync:'C',repair:'S1',note:'Real level-0 array, one build cell, and one RMQ decomposition exist; table levels are not built continuously.'},
  'bitmask-dp': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete mask and one transition exist, but dp values and a continuous state-DAG progression are absent.'},
  'suffix-array': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete string, suffix list, rank pairs, sorted order, or rank-array evolution.'},
  'manacher': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete string, center, mirror, radius values, or rightmost palindrome interval.'},
  'kuhn-matching': {animation:'D',codeSync:'D',repair:'S3',note:'Needs an explicit bipartite graph with matched/unmatched alternating edges and augmenting-path flips.'},
  'miller-rabin': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete n, d, s, base, modular power, or squaring-chain values are shown.'},
  'chinese-remainder-theorem': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete pair of congruences, gcd compatibility test, reduced congruence, or final residue arithmetic.'},
  'sweep-line': {animation:'D',codeSync:'D',repair:'S3',note:'Needs concrete x-events, active y-intervals, covered length, strip width, and accumulated area.'},
  'ntt': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete modular coefficients, root powers, butterfly values, or transform stages.'},
  'prefix-sum': {animation:'A',codeSync:'B',repair:'S0',note:'Excellent continuous prefix values and concrete range query; build mutations often highlight the loop header instead of the assignment.'},
  'two-pointers': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete l/r/value/sum movement on one sorted input; greater/less decisions can still map to the equality branch.'},
  'merge-sort': {animation:'A',codeSync:'C',repair:'S1',note:'Strong recursive split/merge execution, but many element-level merge events map only to a single inplace_merge library call.'},
  'zero-one-bfs': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete deque and edge snapshots exist, but distances and a continuous sequence of 0/1 relaxations are incomplete.'},
  'bellman-ford': {animation:'C',codeSync:'C',repair:'S1',note:'Pass/relax/negative-cycle concepts have concrete snapshots but skip most edge-by-edge distance evolution.'},
  'euler-circuit': {animation:'C',codeSync:'C',repair:'S1',note:'Stack, used edges, dead end and final circuit are meaningful, but Hierholzer traversal/backtracking is not continuous.'},
  'tree-diameter': {animation:'C',codeSync:'C',repair:'S1',note:'Two-sweep endpoints and diameter path are meaningful, but farthest traversals are compressed into repeated call frames.'},
  'centroid-decomposition': {animation:'C',codeSync:'C',repair:'S1',note:'Centroid/components/centroid-tree snapshots are useful; recursive decomposition of each component is skipped.'},
  'fenwick-tree-2d': {animation:'D',codeSync:'D',repair:'S2',note:'Only lowbit/four-prefix phase labels; no concrete matrix coordinates, BIT cells, nested walks, or accumulated values.'},
  'segment-tree-beats': {animation:'D',codeSync:'D',repair:'S3',note:'Needs node-level max1/max2/countMax/sum state and concrete chmin propagation; current range labels cannot explain beats.'},
  'longest-common-subsequence': {animation:'C',codeSync:'C',repair:'S1',note:'One concrete matching-cell transition and final sequence exist, but no actual strings or table fill progression.'},
  'edit-distance': {animation:'C',codeSync:'C',repair:'S1',note:'Base and one dp cell are meaningful, but source/target strings and cell-by-cell table evolution are missing.'},
  'tree-dp': {animation:'C',codeSync:'C',repair:'S2',note:'Uses abstract base/merge placeholders without choosing a concrete tree-DP problem, so no executable dp values exist.'},
  'divide-conquer-dp': {animation:'C',codeSync:'C',repair:'S2',note:'Shows mid and opt bounds conceptually but no concrete dp layer, cost function, candidate values, or best update.'},
  'trie': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete inserted words, trie nodes, character edges, current node, or terminal creation.'},
  'suffix-automaton': {animation:'D',codeSync:'D',repair:'S3',note:'Needs explicit automaton states, transitions, suffix links, clone creation, and redirect operations for one concrete string.'},
  'palindromic-tree': {animation:'D',codeSync:'D',repair:'S3',note:'Needs palindrome nodes, lengths, suffix links, current suffix traversal, and node creation on a concrete string.'},
  'minimum-cut': {animation:'D',codeSync:'D',repair:'S3',note:'Requires a concrete residual graph, reachable S set, T set, saturated crossing edges, and cut capacity.'},
  'euclidean-algorithm': {animation:'D',codeSync:'D',repair:'S2',note:'Only names the gcd invariant and update; no concrete (a,b) remainder sequence is executed.'},
  'modular-inverse': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete a,m,gcd,Bézout coefficient, normalization, or verification arithmetic.'},
  'point-in-polygon': {animation:'D',codeSync:'D',repair:'S2',note:'Needs a concrete polygon, query point, ray, half-open edge tests, crossing count, and boundary case.'},
  'closest-pair': {animation:'D',codeSync:'D',repair:'S3',note:'Needs spatial sweep position, active y-set, eviction boundary, candidate points, and current best distance.'},
  'lagrange-interpolation': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete sample points, basis terms, modular numerators/denominators, term values, or accumulated answer.'},
  'berlekamp-massey': {animation:'D',codeSync:'D',repair:'S3',note:'Current transform-like visual is semantically weak; needs sequence, discrepancy, C/B polynomials, L, m, b, and correction steps.'},
  'difference-array': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete diff construction, boundary events, and prefix restoration on one input; some repeated build steps map to loop headers.'},
  'coordinate-compression': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete sort/unique/rank mapping execution on one dataset; mapping steps can use loop header instead of assignment.'},
  'kadane': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete ending/best values and restart-vs-extend decisions across one array; some iterations map to loop header.'},
  'selection-sort': {animation:'A',codeSync:'B',repair:'S0',note:'Detailed comparisons, min-index updates, swaps, and sorted prefix; comparison events mostly live on the inner-loop header.'},
  'bubble-sort': {animation:'A',codeSync:'B',repair:'S0',note:'Detailed adjacent comparisons, swaps, and fixed suffix progression; some swaps are described while loop header is highlighted.'},
  'quick-sort': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete pivot, store index, comparisons, partition placement, and recursive subranges; a few partition mutations map to loop/header lines.'},
  'quickselect': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete k/pivot decisions exist, but partition itself is hidden and state jumps between unrelated partition outcomes.'},
  'stack': {animation:'C',codeSync:'C',repair:'S1',note:'Useful stack snapshots exist, but initial visual state already contains values before the corresponding push lines execute.'},
  'parentheses-matching': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete input/stack/match state exists, but the trace jumps from three opens directly to one close and then final empty stack.'},
  'queue': {animation:'C',codeSync:'C',repair:'S1',note:'Useful FIFO snapshots exist, but the queue already contains pushed values before push operations are executed.'},
  'deque': {animation:'C',codeSync:'C',repair:'S1',note:'Front/back snapshots are concrete, but generic expansion repeats pre-existing state around push/pop lines instead of showing each mutation.'},
  'binary-heap': {animation:'C',codeSync:'C',repair:'S1',note:'Heap and bubble-up path snapshots exist, but STL priority_queue hides the comparisons/swaps shown conceptually in the animation.'},
  'monotonic-queue': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete deque/incoming/popped snapshots exist, but they jump between windows instead of one continuous sliding-window execution.'},
  'flood-fill': {animation:'C',codeSync:'C',repair:'S1',note:'Painted/frontier/component snapshots are useful, but recursive cell-by-cell expansion and grid geometry are skipped.'},
  'multi-source-bfs': {animation:'C',codeSync:'C',repair:'S1',note:'Sources, queue, layer, and final distances are meaningful; individual discoveries and ownership propagation are compressed.'},
  'dfs': {animation:'C',codeSync:'C',repair:'S1',note:'Call-stack/tree-edge/return snapshots are useful, but recursive calls and returns are not one continuous traversal.'},
  'kruskal': {animation:'D',codeSync:'D',repair:'S2',note:'Only sorted-edge/DSU/MST phase labels are shown; no concrete weighted edge order, component sets, accept/reject decisions, or running cost.'},
  'prim': {animation:'D',codeSync:'D',repair:'S2',note:'Only frontier/take-min/all-joined phase labels; no concrete weighted heap frontier, selected edge, visited set, or running cost.'},
  'bridges': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete disc/low/edge/bridge snapshots exist, but DFS discovery/back-edge/return propagation is not continuous.'},
  'articulation-points': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete low/disc/root-child cut conditions exist, but traversal and child-return updates are compressed.'},
  'euler-tour-flattening': {animation:'C',codeSync:'C',repair:'S1',note:'Euler order and subtree interval are concrete, but entry/recursive traversal/exit timestamps are not shown continuously.'},
  'tree-centroid': {animation:'C',codeSync:'C',repair:'S1',note:'Subtree sizes, heavy child, and final component sizes are useful; the walk toward the centroid is compressed.'},
  'small-to-large': {animation:'D',codeSync:'D',repair:'S2',note:'Only abstract container/merge complexity labels; no concrete colors, child sets, size comparison, swap, or element moves.'},
  'sqrt-decomposition': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete block size, query decomposition, and result exist, but block sums and each partial/full-block accumulation are not executed.'},
  'treap': {animation:'C',codeSync:'C',repair:'S2',note:'Inorder/split snapshots exist, but priorities, actual tree shape, recursive merge choices, and pointer rewiring are missing.'},
  'coin-change': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete coins and amount-6 candidate transition exist, but dp[0..W] is not built continuously.'},
  'tsp-dp': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete mask/u and one transition exist, but state costs and the full-mask return step are not executed continuously.'},
  'rerooting-dp': {animation:'C',codeSync:'C',repair:'S2',note:'Neighbor exclusion/prefix-suffix concepts are present but merge values and one concrete rerooting problem are absent.'},
  'knuth-optimization': {animation:'C',codeSync:'C',repair:'S2',note:'Opt bounds and candidate k values are conceptual; no concrete interval-DP costs or relaxation values are shown.'},
  'rolling-hash': {animation:'D',codeSync:'D',repair:'S2',note:'Only prefix/normalize/comparison phase labels; no concrete string, base/mod, hash[], power[], or substring hash arithmetic.'},
}

const rows=lessons.map((lesson)=>({
  id:lesson.id,
  categoryId:lesson.categoryId,
  visualModel:lesson.visualModel??'none',
  animation:reviewed[lesson.id]?.animation??'UNREVIEWED',
  codeSync:reviewed[lesson.id]?.codeSync??'UNREVIEWED',
  repair:reviewed[lesson.id]?.repair??'UNREVIEWED',
  note:reviewed[lesson.id]?.note??'',
}))

const reviewedRows=rows.filter((row)=>row.animation!=='UNREVIEWED')
const summary={
  total:rows.length,
  reviewed:reviewedRows.length,
  remaining:rows.length-reviewedRows.length,
  animationGrades:Object.fromEntries(['A','B','C','D'].map((grade)=>[grade,reviewedRows.filter((row)=>row.animation===grade).length])),
  repairClasses:Object.fromEntries(['S0','S1','S2','S3'].map((repair)=>[repair,reviewedRows.filter((row)=>row.repair===repair).length])),
}

const md=[
  '# Stage 2 Remediation Matrix',
  '',
  `Reviewed **${summary.reviewed}/${summary.total}** lessons; **${summary.remaining}** remain.`,
  '',
  'This file tracks human semantic review. UNREVIEWED means no A/B/C/D claim has been made yet.',
  '',
  '| Lesson | Category | Visual model | Animation | Code sync | Repair | Note |',
  '|---|---|---|:---:|:---:|:---:|---|',
  ...rows.map((row)=>`| ${row.id} | ${row.categoryId} | ${row.visualModel} | ${row.animation} | ${row.codeSync} | ${row.repair} | ${row.note.replaceAll('|','\\|')} |`),
  '',
].join('\n')

mkdirSync('.tmp',{recursive:true})
writeFileSync('.tmp/stage2-remediation-matrix.json',JSON.stringify({summary,rows},null,2))
writeFileSync('.tmp/stage2-remediation-matrix.md',md)
console.log(JSON.stringify(summary,null,2))
