import { mkdirSync, writeFileSync } from 'node:fs'
import { lessons } from '../src/algorithms'

type Grade = 'A'|'B'|'C'|'D'
type Repair = 'S0'|'S1'|'S2'|'S3'

const reviewed: Record<string,{animation:Grade;codeSync:Grade;repair:Repair;note:string}> = {
  'binary-search': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete interval/midpoint trace; comparison frame can own the wrong primary code line.'},
  'bfs': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete queue/distances; some discovery events map to nearby control-flow lines.'},
  'dijkstra': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete heap/stale/relax trace; some relax events map to loop/header lines.'},
  'segment-tree': {animation:'B',codeSync:'B',repair:'S0',note:'Strong lifecycle; fix query-label/state inconsistency and exact code ownership.'},
  'prefix-xor': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete px/a/XOR evolution; generic 10-step expansion.'},
  'fenwick-tree': {animation:'C',codeSync:'C',repair:'S1',note:'Useful lowbit/path states exist but BIT values do not execute continuously.'},
  'kmp': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete pattern, i, j, pi evolution or fallback chain.'},
  'knapsack-01': {animation:'D',codeSync:'D',repair:'S2',note:'No real dp array mutation across items/capacities.'},
  'tarjan-scc': {animation:'C',codeSync:'C',repair:'S1',note:'Good disc/low/stack snapshots; generic expansion breaks continuous DFS execution.'},
  'digit-dp': {animation:'D',codeSync:'D',repair:'S2',note:'State dimensions are named but no concrete digit-state recursion is executed.'},
  'dinic': {animation:'D',codeSync:'D',repair:'S3',note:'Missing capacities, levels, blocking-flow paths and residual updates.'},
  'meet-in-the-middle': {animation:'D',codeSync:'D',repair:'S2',note:'20 code-position steps from 3 concepts; subset-sum lists never execute.'},
  'monotonic-stack': {animation:'C',codeSync:'C',repair:'S1',note:'Real stack snapshots exist but jump between examples without one continuous input.'},
  'topological-sort': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete indegree/queue exists; missing edge-by-edge decrements and pushes.'},
  'lca-binary-lifting': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete u/v/jump states; missing jump-table reasoning and continuous k scan.'},
  'lazy-segment-tree': {animation:'C',codeSync:'C',repair:'S1',note:'Covered intervals/tags known; 20 code steps spread across only a few semantic states.'},
  'longest-increasing-subsequence': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete tails snapshots exist but do not execute one sequence continuously.'},
  'aho-corasick': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete trie nodes, fail links, text cursor, fallback or reports.'},
  'min-cost-max-flow': {animation:'D',codeSync:'D',repair:'S3',note:'No concrete capacities/costs/path/bottleneck/reverse-edge/cumulative cost state.'},
  'extended-euclid': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete recursion or Bézout coefficient back-substitution.'},
  'rotating-calipers': {animation:'D',codeSync:'D',repair:'S2',note:'No polygon, antipodal pair, area comparison or pointer movement.'},
  'fft': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete coefficients, roots, butterfly values or transform stages.'},
  'linear-search': {animation:'A',codeSync:'A',repair:'S0',note:'Concrete index-by-index execution on one array; state and comparison line remain aligned.'},
  'sliding-window': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete l/r/sum evolution on one input; some add steps map to loop headers rather than the exact sum mutation.'},
  'dsu': {animation:'C',codeSync:'C',repair:'S1',note:'Parent/path-compression/merge snapshots exist, but generic expansion interrupts the actual find/unite sequence.'},
  'floyd-warshall': {animation:'C',codeSync:'C',repair:'S1',note:'One concrete B→E via C relaxation exists; full matrix evolution across k is missing.'},
  'heavy-light-decomposition': {animation:'C',codeSync:'C',repair:'S1',note:'Heavy/light edges and path segments exist, but chain jumps are not executed continuously.'},
  'persistent-segment-tree': {animation:'C',codeSync:'C',repair:'S1',note:'Version roots and copied path are meaningful; node copying and shared-subtree changes need stepwise execution.'},
  'sparse-table': {animation:'C',codeSync:'C',repair:'S1',note:'Real level-0 array, one build cell, and one RMQ decomposition exist; table levels are not built continuously.'},
  'bitmask-dp': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete mask and one transition exist, but dp values and a continuous state-DAG progression are absent.'},
  'suffix-array': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete string, suffix list, rank pairs, sorted order, or rank-array evolution.'},
  'manacher': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete string, center, mirror, radius values, or rightmost palindrome interval.'},
  'kuhn-matching': {animation:'D',codeSync:'D',repair:'S3',note:'Needs an explicit bipartite graph with matched/unmatched alternating edges and augmenting-path flips.'},
  'miller-rabin': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete n, d, s, base, modular power, or squaring-chain values are shown.'},
  'chinese-remainder-theorem': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete pair of congruences, gcd compatibility test, reduced congruence, or final residue arithmetic.'},
  'sweep-line': {animation:'D',codeSync:'D',repair:'S3',note:'Needs concrete x-events, active y-intervals, covered length, strip width, and accumulated area.'},
  'ntt': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete modular coefficients, root powers, butterfly values, or transform stages.'},
  'prefix-sum': {animation:'A',codeSync:'B',repair:'S0',note:'Excellent continuous prefix values and concrete range query; build mutations often highlight the loop header instead of the assignment.'},
  'two-pointers': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete l/r/value/sum movement on one sorted input; greater/less decisions can still map to the equality branch.'},
  'merge-sort': {animation:'A',codeSync:'C',repair:'S1',note:'Strong recursive split/merge execution, but many element-level merge events map only to a single inplace_merge library call.'},
  'zero-one-bfs': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete deque and edge snapshots exist, but distances and a continuous sequence of 0/1 relaxations are incomplete.'},
  'bellman-ford': {animation:'C',codeSync:'C',repair:'S1',note:'Pass/relax/negative-cycle concepts have concrete snapshots but skip most edge-by-edge distance evolution.'},
  'euler-circuit': {animation:'C',codeSync:'C',repair:'S1',note:'Stack, used edges, dead end and final circuit are meaningful, but Hierholzer traversal/backtracking is not continuous.'},
  'tree-diameter': {animation:'C',codeSync:'C',repair:'S1',note:'Two-sweep endpoints and diameter path are meaningful, but farthest traversals are compressed into repeated call frames.'},
  'centroid-decomposition': {animation:'C',codeSync:'C',repair:'S1',note:'Centroid/components/centroid-tree snapshots are useful; recursive decomposition of each component is skipped.'},
  'fenwick-tree-2d': {animation:'D',codeSync:'D',repair:'S2',note:'Only lowbit/four-prefix phase labels; no concrete matrix coordinates, BIT cells, nested walks, or accumulated values.'},
  'segment-tree-beats': {animation:'D',codeSync:'D',repair:'S3',note:'Needs node-level max1/max2/countMax/sum state and concrete chmin propagation; current range labels cannot explain beats.'},
  'longest-common-subsequence': {animation:'C',codeSync:'C',repair:'S1',note:'One concrete matching-cell transition and final sequence exist, but no actual strings or table fill progression.'},
  'edit-distance': {animation:'C',codeSync:'C',repair:'S1',note:'Base and one dp cell are meaningful, but source/target strings and cell-by-cell table evolution are missing.'},
  'tree-dp': {animation:'C',codeSync:'C',repair:'S2',note:'Uses abstract base/merge placeholders without choosing a concrete tree-DP problem, so no executable dp values exist.'},
  'divide-conquer-dp': {animation:'C',codeSync:'C',repair:'S2',note:'Shows mid and opt bounds conceptually but no concrete dp layer, cost function, candidate values, or best update.'},
  'trie': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete inserted words, trie nodes, character edges, current node, or terminal creation.'},
  'suffix-automaton': {animation:'D',codeSync:'D',repair:'S3',note:'Needs explicit automaton states, transitions, suffix links, clone creation, and redirect operations for one concrete string.'},
  'palindromic-tree': {animation:'D',codeSync:'D',repair:'S3',note:'Needs palindrome nodes, lengths, suffix links, current suffix traversal, and node creation on a concrete string.'},
  'minimum-cut': {animation:'D',codeSync:'D',repair:'S3',note:'Requires a concrete residual graph, reachable S set, T set, saturated crossing edges, and cut capacity.'},
  'euclidean-algorithm': {animation:'D',codeSync:'D',repair:'S2',note:'Only names the gcd invariant and update; no concrete (a,b) remainder sequence is executed.'},
  'modular-inverse': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete a,m,gcd,Bézout coefficient, normalization, or verification arithmetic.'},
  'point-in-polygon': {animation:'D',codeSync:'D',repair:'S2',note:'Needs a concrete polygon, query point, ray, half-open edge tests, crossing count, and boundary case.'},
  'closest-pair': {animation:'D',codeSync:'D',repair:'S3',note:'Needs spatial sweep position, active y-set, eviction boundary, candidate points, and current best distance.'},
  'lagrange-interpolation': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete sample points, basis terms, modular numerators/denominators, term values, or accumulated answer.'},
  'berlekamp-massey': {animation:'D',codeSync:'D',repair:'S3',note:'Current transform-like visual is semantically weak; needs sequence, discrepancy, C/B polynomials, L, m, b, and correction steps.'},
  'difference-array': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete diff construction, boundary events, and prefix restoration on one input; some repeated build steps map to loop headers.'},
  'coordinate-compression': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete sort/unique/rank mapping execution on one dataset; mapping steps can use loop header instead of assignment.'},
  'kadane': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete ending/best values and restart-vs-extend decisions across one array; some iterations map to loop header.'},
  'selection-sort': {animation:'A',codeSync:'B',repair:'S0',note:'Detailed comparisons, min-index updates, swaps, and sorted prefix; comparison events mostly live on the inner-loop header.'},
  'bubble-sort': {animation:'A',codeSync:'B',repair:'S0',note:'Detailed adjacent comparisons, swaps, and fixed suffix progression; some swaps are described while loop header is highlighted.'},
  'quick-sort': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete pivot, store index, comparisons, partition placement, and recursive subranges; a few partition mutations map to loop/header lines.'},
  'quickselect': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete k/pivot decisions exist, but partition itself is hidden and state jumps between unrelated partition outcomes.'},
  'stack': {animation:'C',codeSync:'C',repair:'S1',note:'Useful stack snapshots exist, but initial visual state already contains values before the corresponding push lines execute.'},
  'parentheses-matching': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete input/stack/match state exists, but the trace jumps from three opens directly to one close and then final empty stack.'},
  'queue': {animation:'C',codeSync:'C',repair:'S1',note:'Useful FIFO snapshots exist, but the queue already contains pushed values before push operations are executed.'},
  'deque': {animation:'C',codeSync:'C',repair:'S1',note:'Front/back snapshots are concrete, but generic expansion repeats pre-existing state around push/pop lines instead of showing each mutation.'},
  'binary-heap': {animation:'C',codeSync:'C',repair:'S1',note:'Heap and bubble-up path snapshots exist, but STL priority_queue hides the comparisons/swaps shown conceptually in the animation.'},
  'monotonic-queue': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete deque/incoming/popped snapshots exist, but they jump between windows instead of one continuous sliding-window execution.'},
  'flood-fill': {animation:'C',codeSync:'C',repair:'S1',note:'Painted/frontier/component snapshots are useful, but recursive cell-by-cell expansion and grid geometry are skipped.'},
  'multi-source-bfs': {animation:'C',codeSync:'C',repair:'S1',note:'Sources, queue, layer, and final distances are meaningful; individual discoveries and ownership propagation are compressed.'},
  'dfs': {animation:'C',codeSync:'C',repair:'S1',note:'Call-stack/tree-edge/return snapshots are useful, but recursive calls and returns are not one continuous traversal.'},
  'kruskal': {animation:'D',codeSync:'D',repair:'S2',note:'Only sorted-edge/DSU/MST phase labels are shown; no concrete weighted edge order, component sets, accept/reject decisions, or running cost.'},
  'prim': {animation:'D',codeSync:'D',repair:'S2',note:'Only frontier/take-min/all-joined phase labels; no concrete weighted heap frontier, selected edge, visited set, or running cost.'},
  'bridges': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete disc/low/edge/bridge snapshots exist, but DFS discovery/back-edge/return propagation is not continuous.'},
  'articulation-points': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete low/disc/root-child cut conditions exist, but traversal and child-return updates are compressed.'},
  'euler-tour-flattening': {animation:'C',codeSync:'C',repair:'S1',note:'Euler order and subtree interval are concrete, but entry/recursive traversal/exit timestamps are not shown continuously.'},
  'tree-centroid': {animation:'C',codeSync:'C',repair:'S1',note:'Subtree sizes, heavy child, and final component sizes are useful; the walk toward the centroid is compressed.'},
  'small-to-large': {animation:'D',codeSync:'D',repair:'S2',note:'Only abstract container/merge complexity labels; no concrete colors, child sets, size comparison, swap, or element moves.'},
  'sqrt-decomposition': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete block size, query decomposition, and result exist, but block sums and each partial/full-block accumulation are not executed.'},
  'treap': {animation:'C',codeSync:'C',repair:'S2',note:'Inorder/split snapshots exist, but priorities, actual tree shape, recursive merge choices, and pointer rewiring are missing.'},
  'coin-change': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete coins and amount-6 candidate transition exist, but dp[0..W] is not built continuously.'},
  'tsp-dp': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete mask/u and one transition exist, but state costs and the full-mask return step are not executed continuously.'},
  'rerooting-dp': {animation:'C',codeSync:'C',repair:'S2',note:'Neighbor exclusion/prefix-suffix concepts are present but merge values and one concrete rerooting problem are absent.'},
  'knuth-optimization': {animation:'C',codeSync:'C',repair:'S2',note:'Opt bounds and candidate k values are conceptual; no concrete interval-DP costs or relaxation values are shown.'},
  'rolling-hash': {animation:'D',codeSync:'D',repair:'S2',note:'Only prefix/normalize/comparison phase labels; no concrete string, base/mod, hash[], power[], or substring hash arithmetic.'},
  'convex-hull': {animation:'A',codeSync:'B',repair:'S0',note:'Concrete point order, cross products, push/pop hull stacks, and final hull; a few upper-hull events reuse coarse source lines.'},
  'next-greater-element': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete incoming/stack/resolved answers exist, but trace jumps from early pops to a later final stack without continuous input processing.'},
  'tree-isomorphism': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete leaf/child/root encodings exist, but recursive subtree encoding and comparison of two trees are compressed.'},
  'mo-algorithm': {animation:'C',codeSync:'C',repair:'S1',note:'Queries, block size, and one L/R move set exist; sorted query order and add/remove state changes are not executed continuously.'},
  'li-chao-tree': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete lines/domain/midpoint/query candidates exist, but node intervals, line swaps, and recursion path are not continuously visualized.'},
  'z-algorithm': {animation:'D',codeSync:'D',repair:'S2',note:'Only rightmost-box/reuse/all-Z phase labels; no concrete string, i/l/r, mirror z value, extension comparisons, or z array.'},
  'lcp-array': {animation:'D',codeSync:'D',repair:'S2',note:'Only rank/reuse/LCP phase labels; no concrete string, suffix array, rank positions, character comparisons, or h values.'},
  'prime-sieve': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete n, prime/composite table, current p, or multiples being crossed out.'},
  'fast-exponentiation': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete a, exponent bits, result, squaring values, or per-iteration invariant values.'},
  'matrix-exponentiation': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete transition matrix, exponent bits, matrix products, or transformed state vector.'},
  'gaussian-elimination': {animation:'D',codeSync:'D',repair:'S3',note:'Needs a real augmented matrix with pivot selection, row swap, normalization, elimination, rank, and solution classification.'},
  'xor-linear-basis': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete bit vectors, pivot bits, XOR elimination sequence, inserted basis, rank, or max-XOR construction.'},
  'nim': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete pile sizes, running XOR, winning move, or move that makes nim-sum zero.'},
  'sprague-grundy': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete game states, move graph, reachable SG values, mex calculation, or component XOR.'},
  'segment-intersection': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete segments, four orientation values, opposite-side test, or collinear boundary case.'},
  'polygon-area': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete polygon coordinates, per-edge cross products, running signed sum, or final halving.'},
  'prefix-sum-2d': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete grid, prefix cells, inclusion-exclusion numbers, or rectangle query arithmetic.'},
  'counting-sort': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete input multiset, frequency buckets, bucket increments, or emitted sorted values.'},
  'inversion-counting': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete split arrays, merge pointers, right-beats-left event, added m-i count, or running inversion total.'},
  'parallel-binary-search': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete queries, lo/hi/mid intervals, buckets, event sweep state, predicate results, or convergence.'},
  'interval-scheduling': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete intervals, sorted finish order, lastEnd, accept/reject decisions, or selected set.'},
  'interval-covering': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete target range, candidate intervals, covered endpoint, farthest extension, selected intervals, or gap.'},
  'interval-merging': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete intervals, sorted order, current merged component, overlap test, or output list evolution.'},
  'job-scheduling': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete jobs, deadlines/durations, used time, heap contents, or longest-job removal event.'},
  'huffman-coding': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete frequencies, priority queue, two-minimum extraction, merged node, running cost, or code tree.'},
  'fractional-knapsack': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete items, value densities, remaining capacity, taken fraction, or accumulated value.'},
  'largest-rectangle-histogram': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete histogram, stack indices/heights, pop width, area candidate, or running maximum.'},
  'sliding-window-maximum': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete array/window, deque indices/values, expiration/dominance pops, or emitted maxima.'},
  'expression-evaluation': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete token stream, value/operator stacks, precedence reductions, arithmetic operations, or final value.'},
  'shunting-yard': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete infix tokens, operator stack, output queue, precedence pops, parentheses handling, or postfix result.'},
  'connected-components': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete roots, seen sets, and component count snapshots exist, but each component flood is compressed into one jump.'},
  'bipartite-coloring': {animation:'C',codeSync:'C',repair:'S1',note:'Concrete colors and queue snapshots exist, but vertex-by-vertex propagation/conflict checking is not continuous.'},
  'cycle-detection': {animation:'C',codeSync:'C',repair:'S1',note:'White/gray/black stack and a concrete back edge exist, but DFS entry/return transitions are compressed.'},
  'functional-graph': {animation:'D',codeSync:'D',repair:'S2',note:'Only successor/repeat/cycle phase labels; no concrete successor array, walk indices, repeated node, cycle, or in-tree.'},
  'dag-shortest-path': {animation:'D',codeSync:'D',repair:'S2',note:'Only topological/relax/final phase labels; no concrete DAG, order, distances, edge relaxation arithmetic, or updates.'},
  'negative-cycle-reconstruction': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete graph, nth-pass relaxation, parent chain, n-step rewind, or reconstructed cycle.'},
  'boruvka': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete weighted graph, components, cheapest outgoing edges, simultaneous merges, or running MST cost.'},
  'kosaraju-scc': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete graph, first-pass finish order, reversed edges, second-pass DFS, or SCC assignment.'},
  'condensation-graph': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete SCC mapping, original cross-component edges, deduplication, or resulting DAG.'},
  'biconnected-components': {animation:'D',codeSync:'D',repair:'S3',note:'Needs DFS edge stack, disc/low values, articulation boundary event, popped edges, and explicit block membership.'},
  'bridge-tree': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete bridges, 2-edge-connected component labels, contractions, or resulting tree edges.'},
  'block-cut-tree': {animation:'D',codeSync:'D',repair:'S3',note:'Needs explicit block nodes, articulation nodes, membership edges, and the original graph-to-block-cut transformation.'},
  'two-sat': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete clauses, implication edges, SCC IDs, contradiction pair, or assignment derivation.'},
  'weighted-dsu': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete parent tree, potentials, find accumulation, union equation, or difference consistency check.'},
  'rollback-dsu': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete parent/size arrays, history stack, snapshots, unions, or rollback mutations.'},
  'offline-dynamic-connectivity': {animation:'D',codeSync:'D',repair:'S3',note:'Needs edge lifetimes on a time axis, segment-tree time buckets, rollback DSU mutations, leaf queries, and rollback boundaries.'},
  'tree-center': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete tree diameter path, midpoint movement, or one/two-center result.'},
  'tree-distance-queries': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete u/v/LCA, root distances, arithmetic, or highlighted unique path.'},
  'dsu-on-tree': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete subtree sizes, heavy child, kept container, light-subtree additions, answers, or clear operations.'},
  'virtual-tree': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete key vertices, tin order, inserted adjacent LCAs, ancestor stack, or compressed edges.'},
  'prufer-code': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete tree, degree array, min-leaf queue, emitted parent sequence, or degree updates.'},
  'kruskal-reconstruction-tree': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete sorted edges, DSU component roots, new merge nodes/weights, reconstruction tree, or threshold query.'},
  'ford-fulkerson': {animation:'D',codeSync:'D',repair:'S3',note:'Needs a concrete residual graph, augmenting path, bottleneck, forward/reverse capacity mutations, and cumulative flow.'},
  'edmonds-karp': {animation:'D',codeSync:'D',repair:'S3',note:'Needs residual BFS layers/parent path, bottleneck, residual updates, and cumulative max flow.'},
  'push-relabel': {animation:'D',codeSync:'D',repair:'S3',note:'Needs preflow, vertex excess, heights, admissible edges, push amounts, relabels, and active-vertex selection.'},
  'flow-lower-bounds': {animation:'D',codeSync:'D',repair:'S3',note:'Needs lower/upper capacities, transformed residual capacities, node balances, SS/TT edges, t→s edge, and saturation check.'},
  'circulation-demands': {animation:'D',codeSync:'D',repair:'S3',note:'Needs lower-bound imbalances, supply/demand visualization, super source/sink balancing, and feasible circulation values.'},
  'hopcroft-karp': {animation:'D',codeSync:'D',repair:'S3',note:'Needs a concrete bipartite graph, current matching, BFS alternating layers, simultaneous shortest augmenting paths, and flips.'},
  'hungarian': {animation:'D',codeSync:'D',repair:'S3',note:'Needs cost matrix, row/column potentials, slack values, equality graph, alternating tree, and augmentation.'},
  'stable-matching': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete preference tables, free proposer queue, proposals, receiver comparison, displacement, or final stable matching.'},
  'blossom': {animation:'D',codeSync:'D',repair:'S3',note:'Needs alternating forest, odd-cycle blossom detection, contraction base, contracted search, lift, and augmenting-path flip.'},
  'iterative-segment-tree': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete flat tree indices, l/r movement, consumed boundary nodes, partial aggregates, or final merge.'},
  'dynamic-segment-tree': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete huge domain interval, allocated nodes, root-to-leaf path, null subtrees, or sum pull updates.'},
  'merge-sort-tree': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete interval nodes, sorted vectors, query decomposition, binary-search positions, or accumulated count.'},
  'segment-tree-2d': {animation:'D',codeSync:'D',repair:'S3',note:'Needs x-tree nodes, nested y-tree nodes, 2D point update path, rectangle decomposition, and partial aggregates.'},
  'disjoint-sparse-table': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete array, midpoint prefix/suffix tables, l xor r level selection, or two-block combine.'},
  'wavelet-tree': {animation:'D',codeSync:'D',repair:'S3',note:'Needs concrete value partition tree, stable split, prefix rank maps, interval remapping, and kth/count descent.'},
  'wavelet-matrix': {animation:'D',codeSync:'D',repair:'S3',note:'Needs per-bit stable partitions, zero counts/rank prefixes, interval remapping, and bitwise answer construction.'},
  'implicit-treap': {animation:'D',codeSync:'D',repair:'S3',note:'Needs actual treap nodes, subtree sizes, sequence order, split recursion, merge choices, pointer rewiring, and range edit.'},
  'splay-tree': {animation:'D',codeSync:'D',repair:'S3',note:'Needs actual BST shape, parent/grandparent, zig/zig-zig/zig-zag rotations, and root updates.'},
  'link-cut-tree': {animation:'D',codeSync:'D',repair:'S3',note:'Needs represented-tree vs auxiliary-tree state, preferred paths, access/splay rotations, lazy reversals, and link/cut path queries.'},
  'euler-tour-tree': {animation:'D',codeSync:'D',repair:'S3',note:'Needs Euler sequence nodes, component sequence splits/concats, link/cut edge occurrences, and aggregate updates.'},
  'cartesian-tree': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete array, monotone stack, popped right-spine nodes, parent/child links, or resulting Cartesian tree.'},
  'kd-tree': {animation:'D',codeSync:'D',repair:'S3',note:'Needs concrete points, split axes/medians, node bounding boxes, query point, lower bounds, candidate distance, and pruning.'},
  'persistent-dsu': {animation:'D',codeSync:'D',repair:'S3',note:'Needs version graph, persistent parent/size arrays or segment-tree nodes, path-copying union, and historical finds.'},
  'ordered-statistic-tree': {animation:'D',codeSync:'D',repair:'S3',note:'Needs explicit balanced-BST shape, subtree sizes, rotations/rebalancing, kth traversal, and rank accumulation.'},
  'fibonacci-dp': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete n, F0/F1, rolling prev values, cur computation, or final Fibonacci result.'},
  'unbounded-knapsack': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete items, capacity array, forward iteration, source dp state, candidate value, or repeated-item reuse.'},
  'subset-sum': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete numbers, reachable-sum bitset/array, backward updates, newly reachable sums, or target result.'},
  'grid-dp': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete grid, cell values, top/left dependencies, dp arithmetic, fill order, or destination value.'},
  'matrix-chain-multiplication': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete dimensions, interval table, split k candidates, multiplication costs, or chosen parenthesization.'},
  'interval-dp': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete interval problem, dp values, length order, split/boundary candidates, or final interval answer.'},
  'dag-dp': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete DAG, topological order, dp values, edge transitions, or settled states.'},
  'profile-dp': {animation:'D',codeSync:'D',repair:'S3',note:'Needs concrete grid frontier, bitmask occupancy, local placement options, mask shift, and layer/table transitions.'},
  'probability-dp': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete states, transition probabilities, probability mass values, accumulation, or terminal expectation/distribution.'},
  'dp-reconstruction': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete DP problem, parent/choice writes, goal state, backtracking chain, or reconstructed solution.'},
  'monotone-queue-optimization': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete DP values, candidate scores, deque indices, expiry/dominance pops, or optimum transition.'},
  'convex-hull-trick': {animation:'D',codeSync:'D',repair:'S3',note:'Needs concrete DP lines, slopes/intercepts, redundancy intersections, envelope, query x, and selected line/value.'},
  'aliens-optimization': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete penalty lambda, inner-DP result pair, group count monotonicity, binary-search interval, or recovered objective.'},
  'slope-trick': {animation:'D',codeSync:'D',repair:'S3',note:'Needs concrete convex piecewise-linear function, breakpoint heaps, minimizer interval, shifts, and minimum-value changes.'},
  'rabin-karp': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete text/pattern, pattern hash, rolling window hashes, outgoing/incoming characters, hash hit, or verification.'},
  'suffix-tree': {animation:'D',codeSync:'D',repair:'S3',note:'Needs concrete string, compressed edge labels, active point, suffix links, splits, leaves, and extension events.'},
  'duval-lyndon': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete string, i/j/k pointers, character comparisons, reset/repeat behavior, or emitted Lyndon factors.'},
  'minimum-string-rotation': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete doubled string, i/j/k comparisons, discarded start ranges, or final minimum rotation.'},
  'linear-sieve': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete n, lp array, primes list, x/p products, break condition, or one-time composite generation.'},
  'prime-factorization': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete n, trial divisor, repeated division, exponent count, shrinking remainder, or final prime factor.'},
  'euler-totient': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete n, distinct prime factors, result updates result-=result/p, or final phi value.'},
  'pollard-rho': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete composite n, x/y modular walk, |x-y|, gcd values, collision/restart, or discovered factor.'},
  'baby-step-giant-step': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete a,b,m,n, baby table, giant steps, collision, or recovered exponent.'},
  'dot-cross-product': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete vectors, coordinates, dot/cross arithmetic, projection sign, or orientation predicate.'},
  'line-intersection': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete lines/vectors, denominator cross, parameter t, parallel/coincident test, or intersection coordinates.'},
  'point-line-distance': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete point/segment, projection parameter, area/base calculation, endpoint choice, or distance value.'},
  'polar-sort': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete rays/points, half-plane classification, cross-product comparisons, collinear tie-break, or sorted angular order.'},
  'half-plane-intersection': {animation:'D',codeSync:'D',repair:'S3',note:'Needs actual directed half-planes, angle order, deque, adjacent intersections, outside tests, pops, and final feasible polygon.'},
  'circle-intersection': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete centers/radii, center distance, classification, chord base point, h value, or intersection coordinates.'},
  'circle-tangents': {animation:'D',codeSync:'D',repair:'S3',note:'Needs two concrete circles, tangent-type signs, normal-vector solutions, tangent points, and up to four rendered tangent lines.'},
  'smallest-enclosing-circle': {animation:'D',codeSync:'D',repair:'S3',note:'Needs concrete points, current circle, outside test, boundary set of up to three points, diameter/circumcircle updates.'},
  'voronoi-diagram': {animation:'D',codeSync:'D',repair:'S3',note:'Needs concrete sites, sweep line, beach-line arcs, site/circle events, disappearing arcs, bisectors, and Voronoi vertices.'},
  'delaunay-triangulation': {animation:'D',codeSync:'D',repair:'S3',note:'Needs concrete points, current triangulation, circumcircles, conflict cavity, boundary edges, and retriangulation.'},
  'fast-walsh-hadamard-transform': {animation:'D',codeSync:'D',repair:'S2',note:'No concrete coefficient array, bit dimension, butterfly pairs, u/v values, transformed values, pointwise product, or inverse.'},
  'minkowski-sum': {animation:'D',codeSync:'D',repair:'S3',note:'Needs two concrete convex polygons, cyclic edge vectors, cross-angle comparisons, i/j merge progression, accumulated output vertices, and the final A+B polygon.'},
}

const rows=lessons.map((lesson)=>({
  id:lesson.id,
  categoryId:lesson.categoryId,
  visualModel:lesson.visualModel??'none',
  animation:reviewed[lesson.id]?.animation??'UNREVIEWED',
  codeSync:reviewed[lesson.id]?.codeSync??'UNREVIEWED',
  repair:reviewed[lesson.id]?.repair??'UNREVIEWED',
  note:reviewed[lesson.id]?.note??'',
}))

const reviewedRows=rows.filter((row)=>row.animation!=='UNREVIEWED')
const summary={
  total:rows.length,
  reviewed:reviewedRows.length,
  remaining:rows.length-reviewedRows.length,
  animationGrades:Object.fromEntries(['A','B','C','D'].map((grade)=>[grade,reviewedRows.filter((row)=>row.animation===grade).length])),
  repairClasses:Object.fromEntries(['S0','S1','S2','S3'].map((repair)=>[repair,reviewedRows.filter((row)=>row.repair===repair).length])),
}

const md=[
  '# Stage 2 Remediation Matrix',
  '',
  `Reviewed **${summary.reviewed}/${summary.total}** lessons; **${summary.remaining}** remain.`,
  '',
  'This file tracks human semantic review. UNREVIEWED means no A/B/C/D claim has been made yet.',
  '',
  '| Lesson | Category | Visual model | Animation | Code sync | Repair | Note |',
  '|---|---|---|:---:|:---:|:---:|---|',
  ...rows.map((row)=>`| ${row.id} | ${row.categoryId} | ${row.visualModel} | ${row.animation} | ${row.codeSync} | ${row.repair} | ${row.note.replaceAll('|','\\|')} |`),
  '',
].join('\n')

mkdirSync('.tmp',{recursive:true})
writeFileSync('.tmp/stage2-remediation-matrix.json',JSON.stringify({summary,rows},null,2))
writeFileSync('.tmp/stage2-remediation-matrix.md',md)
console.log(JSON.stringify(summary,null,2))
