import type { AlgorithmLesson, CategoryId, Frame } from './algorithms'

type Spec={id:string;index:string;categoryId:CategoryId;subcategory:string;category:string;title:string;zhTitle:string;description:string;complexity:string;accent:string;code:string[];invariant:string;transition:string;result:string;states:[Record<string,string|number|string[]>,Record<string,string|number|string[]>,Record<string,string|number|string[]>]}
const values=[2,5,1,4,9,3,7,6]
const make=(s:Spec):AlgorithmLesson=>{const last=s.code.length;const frames:Frame[]=[
  {title:'定義資料與不變量',explanation:s.invariant,codeLine:s.code[0],codeLines:[1,2],state:s.states[0],values,active:['0'],low:0,high:7},
  {title:'執行核心操作',explanation:s.transition,codeLine:s.code[Math.min(2,last-1)],codeLines:Array.from({length:Math.max(1,last-3)},(_,i)=>i+2),state:s.states[1],values,active:['2','3','4'],low:2,high:4},
  {title:'取得結果並保持正確性',explanation:s.result,codeLine:s.code[last-1],codeLines:[Math.max(1,last-1),last],state:s.states[2],values,accepted:['1','2','3','4','5'],low:1,high:5},
];return {...s,visual:'array',frames}}

const dsAccent='#72e6b7',dpAccent='#ffad72'
export const dataDpLessons:AlgorithmLesson[]=[
  make({id:'fenwick-tree',index:'45',category:'DATA STRUCTURE',categoryId:'data-structures',subcategory:'區間資料結構',title:'Fenwick Tree',zhTitle:'樹狀陣列',description:'以 lowbit 分組維護前綴聚合值。',complexity:'O(log n)',accent:dsAccent,code:['void add(int i, int delta) {','  for (; i <= n; i += i & -i)','    bit[i] += delta;','}','long long prefix(int i) { long long s=0;','  for (; i > 0; i -= i & -i) s += bit[i];','  return s; }'],invariant:'bit[i] 儲存長度 lowbit(i) 的右端區間總和，即 (i-lowbit(i), i]；這些區間是二進位索引自然形成的分組。',transition:'單點 add 沿 i += lowbit(i) 更新所有包含該位置的分組；prefix 則沿 i -= lowbit(i) 拆出互斥區間，恰好覆蓋 [1,i]。',result:'每次索引最低位元至少向更高位進位或被清除，最多 O(log n) 步。區間和可由 prefix(r)-prefix(l-1) 得到。',states:[{lowbit:'i & -i',bit:'bit[4] covers [1,4]'},{operation:'add position 3',path:['3','4','8']},{query:'sum [2,6]',formula:'prefix(6)-prefix(1)'}]}),
  make({id:'lazy-segment-tree',index:'46',category:'DATA STRUCTURE',categoryId:'data-structures',subcategory:'區間資料結構',title:'Lazy Segment Tree',zhTitle:'懶惰標記線段樹',description:'完整覆蓋時延後向子節點傳遞修改。',complexity:'O(log n) per operation',accent:dsAccent,code:['void apply(int p,int l,int r,long long x) {','  tree[p] += x*(r-l+1); lazy[p] += x;','}','void push(int p,int l,int r) {','  if (!lazy[p]) return;','  apply(p*2,l,m,lazy[p]); apply(p*2+1,m+1,r,lazy[p]);','  lazy[p]=0;','}'],invariant:'tree[p] 必須反映節點區間已套用的所有修改；lazy[p] 表示這些修改尚未傳給子節點，而不是尚未作用於 p。',transition:'更新完整覆蓋 p 時直接 apply 並停止遞迴。只有在需要進入子節點前 push，將標記等價地作用到兩個子區間後清空父標記。',result:'延後傳遞不改變任何可觀察查詢結果；一次操作只造訪 O(log n) 個邊界節點與 O(log n) 個完整覆蓋節點。',states:[{node:'[1,8]',lazy:0},{update:'[2,6] += 3',covered:['[3,4]','[5,6]']},{rootSum:'old + 15',pendingTags:['[3,4]:+3','[5,6]:+3']}]}),
  make({id:'persistent-segment-tree',index:'47',category:'DATA STRUCTURE',categoryId:'data-structures',subcategory:'持久化與動態結構',title:'Persistent Segment Tree',zhTitle:'持久化線段樹',description:'更新時只複製根到葉的路徑，保留舊版本。',complexity:'O(log n) new nodes',accent:dsAccent,code:['Node* update(Node* old,int l,int r,int pos,int x) {','  Node* cur = new Node(*old);','  if (l==r) { cur->value=x; return cur; }','  if (pos<=m) cur->left=update(old->left,l,m,pos,x);','  else cur->right=update(old->right,m+1,r,pos,x);','  cur->value=merge(cur->left,cur->right); return cur;','}'],invariant:'每個版本的 root 指向一棵不可變樹；未被此次更新路徑觸及的子樹可以安全與舊版本共享。',transition:'更新位置 pos 時複製每層當前節點，只遞迴一個子節點，另一個 child pointer 沿用 old；回程重新 merge。',result:'新版本僅配置樹高 O(log n) 個節點，舊 root 的所有指標未改變，因此可同時查詢任意歷史版本。',states:[{versions:['root0'],sharedNodes:'all'},{update:'version0 pos=5→10',copiedPath:['[1,8]','[5,8]','[5,6]','[5,5]']},{versions:['root0','root1'],newNodes:4}]}),
  make({id:'sparse-table',index:'48',category:'DATA STRUCTURE',categoryId:'data-structures',subcategory:'區間資料結構',title:'Sparse Table',zhTitle:'稀疏表',description:'預處理所有 2 的冪次區間，O(1) 回答冪等查詢。',complexity:'Build O(n log n) · Query O(1)',accent:dsAccent,code:['for (int i=0;i<n;++i) st[0][i]=a[i];','for (int k=1;(1<<k)<=n;++k)','  for (int i=0;i+(1<<k)<=n;++i)','    st[k][i]=min(st[k-1][i],st[k-1][i+(1<<(k-1))]);','int k=log2(r-l+1);','return min(st[k][l],st[k][r-(1<<k)+1]);'],invariant:'st[k][i] 儲存長度 2^k、左端 i 的區間答案；由兩個相鄰 2^(k−1) 區間合併。',transition:'對 RMQ 選 k=floor(log2(length))，用從左右端開始的兩個長度 2^k 區間覆蓋查詢；它們可以重疊。',result:'min/max/gcd 具有冪等性，重複元素不影響答案，所以兩次查表即可；sum 不具冪等性，不能使用重疊版本。',states:[{level0:['2','5','1','4','9','3','7','6']},{build:'st[2][2] = min([2,3],[4,5])',value:1},{query:'min [2,6]',blocks:['[2,5]','[3,6]'],answer:1}]}),
  make({id:'sqrt-decomposition',index:'49',category:'DATA STRUCTURE',categoryId:'data-structures',subcategory:'區間資料結構',title:'Square Root Decomposition',zhTitle:'分塊',description:'把陣列切成約 √n 大小的區塊。',complexity:'O(√n) per query',accent:dsAccent,code:['int blockSize = sqrt(n) + 1;','for (int i=0;i<n;++i) block[i/blockSize] += a[i];','long long query(int l,int r) {','  while (l<=r && l%blockSize) answer+=a[l++];','  while (l+blockSize-1<=r) answer+=block[l/blockSize],l+=blockSize;','  while (l<=r) answer+=a[l++];','  return answer; }'],invariant:'每個 block 保存整個固定區塊的聚合值；原陣列仍保存個別元素以處理左右不完整區塊。',transition:'查詢先逐元素走到區塊邊界，中段一次跨完整 block，最後處理尾端；最多兩個零碎區加約 n/B 個完整區。',result:'選 B≈√n 平衡 B 與 n/B，得到 O(√n)。簡單、常數小，適合操作不容易在線段樹合併的情況。',states:[{blockSize:3,blocks:['[0,2]','[3,5]','[6,7]']},{query:'[1,6]',parts:['1..2','block 1','6']},{answer:29,cost:'2+1 blocks+1'}]}),
  make({id:'mo-algorithm',index:'50',category:'OFFLINE',categoryId:'search-sort',subcategory:'離線查詢',title:"Mo's Algorithm",zhTitle:'莫隊演算法',description:'重新排序查詢，使區間端點總移動量受控。',complexity:'O((n+q)√n)',accent:'#78d8ff',code:['sort(queries.begin(),queries.end(),byBlockThenRight);','int L=0,R=-1;','for (auto [l,r,id] : queries) {','  while (L>l) add(--L); while (R<r) add(++R);','  while (L<l) remove(L++); while (R>r) remove(R--);','  answer[id]=current;','}'],invariant:'current 永遠等於目前維護區間 [L,R] 的答案；add/remove 必須能在端點移動一格時更新狀態。',transition:'先依左端 block 排序，再依右端排序；同一 block 中 L 總移動 O(√n)，R 單調掃過 O(n)。奇偶 block 可反轉 R 降低常數。',result:'答案依原 id 寫回，不受離線順序影響。演算法適合無修改、可 O(1) add/remove、但不易做區間合併的查詢。',states:[{queries:['[0,3]','[2,6]','[1,4]'],blockSize:3},{current:'[0,3]→[1,4]',moves:['remove 0','add 4']},{answers:'restored by id',totalMoves:'O((n+q)√n)'}]}),
  make({id:'treap',index:'51',category:'BST',categoryId:'data-structures',subcategory:'平衡搜尋樹',title:'Treap',zhTitle:'隨機平衡搜尋樹',description:'同時維持 Key 的 BST 與 Priority 的 Heap 性質。',complexity:'Expected O(log n)',accent:dsAccent,code:['pair<Node*,Node*> split(Node* t,int key);','Node* merge(Node* a,Node* b) {','  if (!a||!b) return a?a:b;','  if (a->priority < b->priority) { a->right=merge(a->right,b); return a; }','  b->left=merge(a,b->left); return b;','}'],invariant:'中序遍歷依 key 遞增；priority 同時滿足 heap。隨機且互異的 priority 等價於隨機 BST 形狀。',transition:'merge 假設 a 所有 key<b；比較根 priority 決定新根，再只遞迴一側。split 依 key 將樹切成兩棵並保持兩項性質。',result:'插入可 split 成 <key 與 ≥key，merge 左、新節點、右；隨機高度期望 O(log n)，但不是最壞保證。',states:[{inorder:['1','2','4','5','7'],heap:'priority parent < child'},{operation:'split key=4',left:['1','2'],right:['4','5','7']},{operation:'merge',expectedHeight:'O(log n)'}]}),
  make({id:'li-chao-tree',index:'52',category:'DATA STRUCTURE',categoryId:'data-structures',subcategory:'持久化與動態結構',title:'Li Chao Tree',zhTitle:'李超線段樹',description:'維護直線集合在指定 x 的最小值。',complexity:'O(log C)',accent:dsAccent,code:['void add(Line nw,int p,int l,int r) {','  int m=(l+r)/2; bool left=nw(l)<line[p](l), mid=nw(m)<line[p](m);','  if (mid) swap(nw,line[p]);','  if (l==r) return;','  if (left!=mid) add(nw,p*2,l,m);','  else add(nw,p*2+1,m+1,r);','}'],invariant:'每個節點保存一條在該區間中點較優的直線；其餘直線只可能在至多一側重新勝出。',transition:'比較新舊直線在左端與中點的優劣；中點較優者留在節點。兩直線至多交一次，因此落敗者只需遞迴可能翻轉優劣的一側。',result:'查詢 x 沿根到葉，取路徑上所有直線值的最小值。每層只走一側，所以加入與查詢皆 O(log C)。',states:[{lines:['y=2x+1','y=-x+8'],domain:'[0,8]'},{mid:4,keep:'-x+8',recurse:'left with 2x+1'},{query:'x=3',candidates:['7','5'],answer:5}]}),
  make({id:'knapsack-01',index:'53',category:'DP',categoryId:'dynamic-programming',subcategory:'經典 DP',title:'0/1 Knapsack',zhTitle:'零一背包',description:'每件物品最多選一次，以容量作狀態。',complexity:'O(nW)',accent:dpAccent,code:['vector<int> dp(W+1,0);','for (auto [weight,value] : items)','  for (int w=W; w>=weight; --w)','    dp[w]=max(dp[w],dp[w-weight]+value);','return dp[W];'],invariant:'處理完前 i 件物品後，dp[w] 是容量不超過 w 的最大價值；尚未處理物品不會出現在狀態中。',transition:'對新物品比較不選 dp[w] 與選擇 dp[w-weight]+value。容量必須由大到小，避免同一輪讀到已包含此物品的狀態而重複選取。',result:'每個物品只更新一次所有容量，最後 dp[W] 是所有合法子集合最大值。若正向掃描則變成完全背包。',states:[{item:'(weight=3,value=5)',dp:'before item i'},{capacity:7,choices:['dp[7]','dp[4]+5'],direction:'W→weight'},{answer:'dp[W]',selected:'each item ≤1'}]}),
  make({id:'coin-change',index:'54',category:'DP',categoryId:'dynamic-programming',subcategory:'經典 DP',title:'Coin Change',zhTitle:'硬幣找零 DP',description:'以金額為狀態求最少硬幣或方案數。',complexity:'O(nW)',accent:dpAccent,code:['vector<int> dp(W+1,INF); dp[0]=0;','for (int amount=1; amount<=W; ++amount)','  for (int coin : coins)','    if (coin<=amount)','      dp[amount]=min(dp[amount],dp[amount-coin]+1);','return dp[W];'],invariant:'dp[x] 是湊出金額 x 的最少硬幣數；dp[0]=0 是所有轉移的基底，不可達狀態為 INF。',transition:'最佳解最後一定使用某個 coin；移除最後硬幣後留下 amount-coin 的最佳子問題，因此枚舉最後硬幣取最小值。',result:'金額由小到大確保依賴已完成。若求方案數，改用加法並注意迴圈順序決定是否區分排列。',states:[{coins:['1','3','4'],dp0:0},{amount:6,choices:['dp5+1','dp3+1','dp2+1'],best:2},{answer:'3+3',minimumCoins:2}]}),
  make({id:'longest-common-subsequence',index:'55',category:'DP',categoryId:'dynamic-programming',subcategory:'經典 DP',title:'Longest Common Subsequence',zhTitle:'最長共同子序列',description:'比較兩個前綴最後字元，建立二維 DP。',complexity:'O(nm)',accent:dpAccent,code:['for (int i=1;i<=n;++i)','  for (int j=1;j<=m;++j)','    if (a[i-1]==b[j-1]) dp[i][j]=dp[i-1][j-1]+1;','    else dp[i][j]=max(dp[i-1][j],dp[i][j-1]);','return dp[n][m];'],invariant:'dp[i][j] 是 a 前 i 字元與 b 前 j 字元的 LCS 長度；空前綴列與欄為 0。',transition:'最後字元相同時存在包含它們的最優解，從兩邊前綴加 1；不同時至少捨棄其中一個最後字元，取兩種子問題較大者。',result:'依賴只在左、上、左上，因此按列填表合法。回溯選擇來源可重建一條實際 LCS。',states:[{prefixes:'A[0..i), B[0..j)',base:'dp[0][*]=0'},{chars:'A[i-1]=C, B[j-1]=C',transition:'diagonal + 1'},{length:'dp[n][m]=4',sequence:'BCAB'}]}),
  make({id:'longest-increasing-subsequence',index:'56',category:'DP',categoryId:'dynamic-programming',subcategory:'經典 DP',title:'Longest Increasing Subsequence',zhTitle:'最長遞增子序列',description:'以 tails 維護各長度的最小結尾值。',complexity:'O(n log n)',accent:dpAccent,code:['vector<int> tails;','for (int x : a) {','  auto it=lower_bound(tails.begin(),tails.end(),x);','  if (it==tails.end()) tails.push_back(x);','  else *it=x;','}','return tails.size();'],invariant:'tails[len−1] 是目前所有長度 len 遞增子序列中最小可能結尾；tails 嚴格遞增，但本身不一定是一條原序列子序列。',transition:'lower_bound 找第一個 ≥x 的結尾並替換，使相同長度未來更容易延伸；若不存在，x 可延伸目前最長長度。',result:'替換不改變可達長度，只改善結尾；push 才使 LIS 長度增加。若要重建序列，需額外保存前驅與來源索引。',states:[{tails:['2'],incoming:5},{incoming:4,replace:'5→4',tails:['2','4']},{tails:['1','3','7'],length:3}]}),
  make({id:'edit-distance',index:'57',category:'DP',categoryId:'dynamic-programming',subcategory:'經典 DP',title:'Edit Distance',zhTitle:'編輯距離',description:'以前綴狀態計算插入、刪除、替換最少次數。',complexity:'O(nm)',accent:dpAccent,code:['dp[i][0]=i; dp[0][j]=j;','for (int i=1;i<=n;++i) for (int j=1;j<=m;++j) {','  int cost=(a[i-1]==b[j-1]?0:1);','  dp[i][j]=min({dp[i-1][j]+1, dp[i][j-1]+1,','                dp[i-1][j-1]+cost});','}','return dp[n][m];'],invariant:'dp[i][j] 表示把 a 的前 i 字元轉成 b 的前 j 字元所需最少操作；空字串邊界只能全插入或全刪除。',transition:'最優操作最後一步只可能刪除 a 末字元、插入 b 末字元、或匹配/替換兩個末字元；三種情況覆蓋所有方案。',result:'子問題規模都嚴格縮小，因此二維表順序有效。保存選中的轉移即可重建具體編輯腳本。',states:[{base:'dp[i][0]=i, dp[0][j]=j'},{cell:'dp[4][3]',choices:['delete','insert','replace']},{distance:3,script:['replace','insert','delete']}]}),
  make({id:'bitmask-dp',index:'58',category:'DP',categoryId:'dynamic-programming',subcategory:'狀態壓縮',title:'Bitmask DP',zhTitle:'位元遮罩動態規劃',description:'以整數位元集合表示已選元素。',complexity:'O(2ⁿ·n)',accent:dpAccent,code:['for (int mask=0; mask<(1<<n); ++mask)','  for (int x=0; x<n; ++x)','    if (!(mask>>x&1))','      dp[mask|(1<<x)] = min(dp[mask|(1<<x)], dp[mask]+cost(mask,x));'],invariant:'mask 的第 x 位為 1 代表 x 已處理；dp[mask] 是恰好完成該集合的最佳成本。',transition:'從 mask 選一個尚未包含的 x，轉到 mask|(1<<x)。位元測試避免重複選擇，且新狀態 popcount 多 1，形成 DAG。',result:'共有 2^n 個集合，每個最多枚舉 n 個下一元素。適合 n 約 20，並能精確表示選取歷史。',states:[{mask:'0101',selected:['0','2']},{choose:3,nextMask:'1101',cost:'dp[0101]+c'},{target:'1111',answer:'dp[(1<<n)-1]'}]}),
  make({id:'tsp-dp',index:'59',category:'DP',categoryId:'dynamic-programming',subcategory:'狀態壓縮',title:'Traveling Salesman DP',zhTitle:'旅行推銷員狀壓 DP',description:'記錄已訪集合與最後所在城市。',complexity:'O(2ⁿn²)',accent:dpAccent,code:['dp[1<<start][start]=0;','for (int mask=0; mask<(1<<n); ++mask)','  for (int u=0;u<n;++u) if (mask>>u&1)','    for (int v=0;v<n;++v) if (!(mask>>v&1))','      dp[mask|1<<v][v]=min(dp[mask|1<<v][v],dp[mask][u]+w[u][v]);'],invariant:'dp[mask][u] 是從 start 出發，恰好走過 mask 且最後位於 u 的最短路徑；u 必須包含於 mask。',transition:'枚舉未訪 v，把 u→v 作為最後一條邊。所有到新狀態的 Hamilton 路徑，都有唯一的倒數第二城市 u。',result:'完成全 mask 後再加 u→start 可得到最短巡迴。狀態數 2^n·n，轉移再乘 n。',states:[{state:'mask=0101,u=2',cost:7},{transition:'2→3',next:'1101,3',candidate:11},{fullMask:'1111',tourCost:'min dp+return'}]}),
  make({id:'tree-dp',index:'60',category:'DP',categoryId:'dynamic-programming',subcategory:'區間與樹 DP',title:'Tree DP',zhTitle:'樹形動態規劃',description:'由子樹答案合併父節點狀態。',complexity:'O(V)',accent:dpAccent,code:['void dfs(int u,int p) {','  dp[u]=base(u);','  for (int v:tree[u]) if (v!=p) {','    dfs(v,u);','    dp[u]=merge(dp[u],dp[v]);','  }','}'],invariant:'dfs(u) 返回時，dp[u] 已正確描述整個以 u 為根子樹；不同 child 子樹互不相交，只透過 u 連接。',transition:'先遞迴取得每個 child 的完整答案，再依題目定義 merge。因樹無環，排除 parent 後不存在尚未處理的交叉依賴。',result:'每條父子邊只在合併時處理常數次，總成本 O(V)。具體狀態可表示獨立集、距離、選取數等。',states:[{node:'F',dpF:'base leaf'},{node:'B',children:['D','E'],merge:'dp[D] ⊕ dp[E]'},{root:'A',answer:'dp[A]'}]}),
  make({id:'rerooting-dp',index:'61',category:'DP',categoryId:'dynamic-programming',subcategory:'區間與樹 DP',title:'Rerooting DP',zhTitle:'換根動態規劃',description:'以兩次 DFS 求每個節點作根時的答案。',complexity:'O(V)',accent:dpAccent,code:['dfs1(u,p); // child → parent contributions','dfs2(u,p,fromParent) {','  prefix/suffix merge all neighbor contributions;','  answer[u]=merge(all);','  for (child v) dfs2(v,u,allExceptV);','}'],invariant:'第一遍取得每條邊由 child 側傳向 parent 的貢獻；第二遍在 u 已知所有鄰居方向的貢獻。',transition:'傳給 child v 時必須排除 v 原本對 u 的貢獻；用 prefix/suffix 可在 O(1) 得到 allExceptV，避免每個 child 重算。',result:'每條有向邊貢獻計算一次，得到所有可能根的答案而非 O(V²) 重跑 DP。',states:[{down:'child→parent computed'},{node:'B',allNeighbors:['A','D','E'],exclude:'D'},{answers:['root A','root B','…'],cost:'O(V)'}]}),
  make({id:'divide-conquer-dp',index:'62',category:'DP OPT',categoryId:'dynamic-programming',subcategory:'DP 最佳化',title:'Divide & Conquer DP Optimization',zhTitle:'分治 DP 最佳化',description:'利用最佳轉移點單調性縮小搜尋範圍。',complexity:'O(kn log n)',accent:dpAccent,code:['void solve(int l,int r,int optL,int optR) {','  if (l>r) return; int mid=(l+r)/2;','  for (int j=optL;j<=min(mid,optR);++j) relax(mid,j);','  solve(l,mid-1,optL,best[mid]);','  solve(mid+1,r,best[mid],optR);','}'],invariant:'假設 best[i] 單調不減。solve(l,r,optL,optR) 保證該區間所有最佳轉移點都落在候選界內。',transition:'先暴力求 mid 的 best[mid]，單調性讓左半候選上界縮成 best[mid]、右半下界也縮成 best[mid]，再遞迴。',result:'每層所有 mid 的候選掃描總量 O(n)，遞迴深度 O(log n)，每一 DP layer 由 O(n²) 降為 O(n log n)。',states:[{range:'i∈[1,n]',opt:'[0,n]'},{mid:4,bestMid:2,leftOpt:'[0,2]',rightOpt:'[2,n]'},{complexity:'per layer O(n log n)',requirement:'monotone opt'}]}),
  make({id:'knuth-optimization',index:'63',category:'DP OPT',categoryId:'dynamic-programming',subcategory:'DP 最佳化',title:'Knuth Optimization',zhTitle:'Knuth 四邊形最佳化',description:'利用區間 DP 最佳切點的夾擠單調性。',complexity:'O(n²)',accent:dpAccent,code:['for (int len=2;len<=n;++len)','  for (int l=0;l+len<=n;++l) { int r=l+len;','    for (int k=opt[l][r-1]; k<=opt[l+1][r]; ++k)','      relax(dp[l][r],k);','  }'],invariant:'對滿足四邊形不等式的成本，最佳切點滿足 opt[l][r−1]≤opt[l][r]≤opt[l+1][r]。',transition:'計算區間 [l,r] 時，只需在兩個已知相鄰區間最佳點之間枚舉 k；依區間長度遞增確保界已完成。',result:'所有區間的候選範圍望遠鏡式合計 O(n²)，將典型 O(n³) 區間 DP 降為 O(n²)；使用前必須證明條件。',states:[{interval:'[l,r]',bounds:'opt[l][r-1]..opt[l+1][r]'},{candidateK:['3','4'],best:4},{complexity:'O(n²)',precondition:'quadrangle inequality'}]}),
]
