import type { AlgorithmLesson, Frame } from './algorithms'

type Phase = {
  title: string; explanation: string; lines: number[]; state: Record<string, string | number | string[]>
  values?: number[]; active?: number[]; accepted?: number[]; muted?: number[]; low?: number; high?: number; mid?: number
}

type Spec = Omit<AlgorithmLesson, 'frames' | 'visual' | 'points' | 'edges'> & { values: number[]; phases: Phase[] }

const make = (spec: Spec): AlgorithmLesson => ({
  ...spec,
  visual: 'array',
  frames: spec.phases.map((phase): Frame => ({
    title: phase.title,
    explanation: phase.explanation,
    codeLine: spec.code[phase.lines[0] - 1]?.trim() ?? '',
    codeLines: phase.lines,
    state: phase.state,
    values: phase.values ?? spec.values,
    active: phase.active?.map(String),
    accepted: phase.accepted?.map(String),
    muted: phase.muted?.map(String),
    low: phase.low ?? 0,
    high: phase.high ?? (phase.values ?? spec.values).length - 1,
    mid: phase.mid,
  })),
})

const array = [7, 2, 9, 4, 1, 8, 5, 3]

export const foundationLessons: AlgorithmLesson[] = [
  make({ id:'linear-search',index:'06',category:'SEARCH',categoryId:'search-sort',subcategory:'陣列技巧',title:'Linear Search',zhTitle:'線性搜尋',description:'依序檢查元素，直到找到目標或走完整個陣列。',complexity:'O(n)',accent:'#78d8ff',animationVersion:2,sources:[{label:'USACO',title:'Competitive Programming 2 · Linear Search',url:'https://usaco.guide/CP2.pdf'}],values:[7,2,9,4,1,8,5],code:['int linearSearch(vector<int>& a, int target) {','  for (int i = 0; i < a.size(); ++i) {','    if (a[i] == target) return i;','  }','  return -1;','}'],phases:[
    {title:'先確認搜尋條件',explanation:'目標是 8，而陣列沒有排序。因為右邊的值沒有單調規律，我們不能像二分搜尋一樣跳過一整段。',lines:[1],state:{target:8,input:'[7,2,9,4,1,8,5]',invariant:'只排除已親自比較過的位置'},low:0,high:6},
    {title:'指標 i 從 0 開始',explanation:'for 迴圈把 i 設成 0。此時索引 0 是唯一正在檢查的位置，索引 1 到 6 都仍可能是答案。',lines:[2],state:{index:0,checked:'none',unchecked:'[0,6]'},active:[0],low:0,high:6},
    {title:'比較 a[0] 與目標',explanation:'a[0]=7，不等於 8，所以索引 0 不可能是答案；但這次比較沒有告訴我們其他位置的內容。',lines:[3],state:{index:0,comparison:'7 == 8 → false',decision:'排除索引 0'},active:[0],muted:[0],low:1,high:6},
    {title:'i 前進到索引 1',explanation:'迴圈執行 ++i，現在比較 a[1]=2。2≠8，因此只新增排除索引 1。',lines:[2,3],state:{index:1,comparison:'2 == 8 → false',checked:'[0,1]'},active:[1],muted:[0,1],low:2,high:6},
    {title:'檢查索引 2',explanation:'a[2]=9 仍不等於 8。即使 9 已經大於 8，也不能停止，因為未排序陣列的後面仍可能再次變小或出現 8。',lines:[2,3],state:{index:2,comparison:'9 == 8 → false',reason:'unsorted → cannot stop'},active:[2],muted:[0,1,2],low:3,high:6},
    {title:'檢查索引 3',explanation:'a[3]=4，不符合條件。現在已確定前四格都不是答案，搜尋邊界向右移到索引 4。',lines:[2,3],state:{index:3,comparison:'4 == 8 → false',checked:'[0,3]'},active:[3],muted:[0,1,2,3],low:4,high:6},
    {title:'檢查索引 4',explanation:'a[4]=1，也不等於 8。到目前為止每個位置只被讀取一次，沒有回頭。',lines:[2,3],state:{index:4,comparison:'1 == 8 → false',visits:5},active:[4],muted:[0,1,2,3,4],low:5,high:6},
    {title:'指標移到索引 5',explanation:'迴圈再次執行 ++i。索引 0 到 4 已排除，現在只需要判斷 a[5]。',lines:[2],state:{index:5,checked:'[0,4]',candidates:'[5,6]'},active:[5],muted:[0,1,2,3,4],low:5,high:6},
    {title:'a[5] 正好等於 8',explanation:'這次條件 a[i]==target 為真。索引 5 是從左到右遇到的第一個 8，因此不需要再檢查索引 6。',lines:[3],state:{index:5,comparison:'8 == 8 → true',decision:'return immediately'},active:[5],accepted:[5],muted:[0,1,2,3,4],low:5,high:5},
    {title:'回傳索引 5，搜尋完成',explanation:'函式回傳 5。這次共比較 6 次；若目標不存在或位於最後一格，最壞要比較 n 次，所以時間複雜度是 O(n)。',lines:[3],state:{result:5,comparisons:6,worstCase:'n comparisons'},active:[5],accepted:[5],muted:[0,1,2,3,4,6],low:5,high:5},
  ]}),
  make({ id:'two-pointers',index:'07',category:'ARRAY',categoryId:'search-sort',subcategory:'陣列技巧',title:'Two Pointers',zhTitle:'雙指標',description:'利用排序後的單調性向內移動兩個端點。',complexity:'O(n)',accent:'#78d8ff',animationVersion:2,sources:[{label:'USACO',title:'USACO Guide · Two Pointers',url:'https://usaco.guide/silver/two-pointers'}],values:[1,2,4,6,8,11,15],code:['bool twoSum(vector<int>& a, int target) {','  int l = 0, r = a.size() - 1;','  while (l < r) {','    int sum = a[l] + a[r];','    if (sum == target) return true;','    if (sum < target) ++l;','    else --r;','  }','  return false;','}'],phases:[
    {title:'先確認陣列已排序',explanation:'目標是找兩個數相加等於 15。陣列由小到大排序，才有「右移會變大、左移會變小」的單調性。',lines:[1],state:{target:15,prerequisite:'sorted ascending',goal:'a[l] + a[r] = 15'},low:0,high:6},
    {title:'兩個指標站在最外側',explanation:'令 l=0 指向最小值 1，r=6 指向最大值 15。所有尚未排除的配對都位於兩個指標之間。',lines:[2],state:{l:0,r:6,leftValue:1,rightValue:15},active:[0,6],low:0,high:6},
    {title:'計算第一組總和',explanation:'sum=1+15=16，比目標 15 大。這組配對不能使用，但我們還要判斷該移動哪一端。',lines:[3,4],state:{formula:'1 + 15',sum:16,target:15},active:[0,6],low:0,high:6},
    {title:'總和太大，只能左移右指標',explanation:'固定最小值 1 時，若連最大值都太大，就把 r 左移以取得更小的數。保留 r=6 只會讓其他左值更大，因此可安全排除。',lines:[5,6,7],state:{comparison:'16 > 15',decision:'r--',eliminated:'right endpoint 15'},active:[6],muted:[6],low:0,high:5},
    {title:'新候選是 1 與 11',explanation:'現在 l=0、r=5，sum=1+11=12。總和變得太小，需要讓其中一個數增加。',lines:[3,4],state:{l:0,r:5,formula:'1 + 11',sum:12},active:[0,5],muted:[6],low:0,high:5},
    {title:'總和太小，右移左指標',explanation:'固定 11 時，1 已經太小；更小的左值也不可能成功。因此執行 ++l，安全排除索引 0。',lines:[5,6],state:{comparison:'12 < 15',decision:'l++',eliminated:'left endpoint 1'},active:[0],muted:[0,6],low:1,high:5},
    {title:'檢查 2 與 11',explanation:'l=1、r=5，sum=2+11=13，仍小於 15。依相同單調性，左指標還要再右移。',lines:[3,4],state:{l:1,r:5,formula:'2 + 11',sum:13},active:[1,5],muted:[0,6],low:1,high:5},
    {title:'再次排除過小的左端',explanation:'13<15，所以 ++l。索引 1 的值 2 不可能和目前或更小的右端形成 15。',lines:[5,6],state:{comparison:'13 < 15',decision:'l++',eliminated:'left endpoint 2'},active:[1],muted:[0,1,6],low:2,high:5},
    {title:'4 與 11 正好命中',explanation:'現在 sum=4+11=15，條件 sum==target 成立。兩個指標指出答案索引 2 與 5。',lines:[3,4,5],state:{l:2,r:5,formula:'4 + 11',comparison:'15 == 15'},active:[2,5],accepted:[2,5],muted:[0,1,6],low:2,high:5},
    {title:'立即回傳 true',explanation:'找到一組合法配對後即可停止。l 只向右、r 只向左，每個指標最多走 n 格，因此總時間是 O(n)。',lines:[5],state:{result:'true',pair:'(4,11)',movement:'l and r never move backward'},active:[2,5],accepted:[2,5],muted:[0,1,3,4,6],low:2,high:5},
  ]}),
  make({ id:'sliding-window',index:'08',category:'ARRAY',categoryId:'search-sort',subcategory:'陣列技巧',title:'Sliding Window',zhTitle:'滑動視窗',description:'維護連續區間，讓左右端點只向前移動。',complexity:'O(n)',accent:'#78d8ff',animationVersion:2,sources:[{label:'USACO',title:'USACO Guide · Two Pointers / Sliding Window',url:'https://usaco.guide/silver/two-pointers'}],values:[2,1,3,2,4,1,2],code:['int minWindow(vector<int>& a, int target) {','  int l = 0, sum = 0, answer = INF;','  for (int r = 0; r < a.size(); ++r) {','    sum += a[r];','    while (sum >= target) {','      answer = min(answer, r-l+1);','      sum -= a[l++];','    }','  }','  return answer;','}'],phases:[
    {title:'定義視窗與目標',explanation:'要找總和至少 7 的最短連續子陣列。因為元素皆為正數，右端加入元素只會讓 sum 增加，左端移除只會讓 sum 減少。',lines:[1],state:{target:7,goal:'minimum length with sum ≥ 7',prerequisite:'all values are positive'},low:0,high:0},
    {title:'初始化空視窗',explanation:'l=0、sum=0、answer=INF。右指標 r 將逐格加入元素，answer 則保存目前看過的最短可行長度。',lines:[2],state:{l:0,sum:0,answer:'∞'},low:0,high:0},
    {title:'r=0，加入數字 2',explanation:'sum 由 0 變成 2，小於 7。現在不能縮左端，否則總和只會更小，所以讓 r 繼續向右。',lines:[3,4],state:{window:'[0,0]',operation:'+ a[0]=2',sum:2},active:[0],low:0,high:0},
    {title:'r=1，加入數字 1',explanation:'視窗變成 [0,1]，sum=3，仍未達標。維持 l=0 並繼續擴張。',lines:[3,4],state:{window:'[0,1]',operation:'+ a[1]=1',sum:3},active:[1],low:0,high:1},
    {title:'r=2，加入數字 3',explanation:'視窗 [0,2] 的總和是 6，還差 1。由於 sum<target，while 條件為假。',lines:[3,4,5],state:{window:'[0,2]',sum:6,comparison:'6 ≥ 7 → false'},active:[2],low:0,high:2},
    {title:'r=3，第一次達到目標',explanation:'加入 2 後 sum=8，視窗 [0,3] 已可行。第一次更新 answer=min(INF,4)=4。',lines:[3,4,5,6],state:{window:'[0,3]',sum:8,answer:'∞ → 4'},active:[0,3],accepted:[0,1,2,3],low:0,high:3},
    {title:'嘗試從左端縮短',explanation:'移除 a[0]=2，l 變成 1、sum 變成 6。因為 6<7，不能再縮，重新交回右指標擴張。',lines:[7,8],state:{removed:'a[0]=2',window:'[1,3]',sum:6},active:[0],muted:[0],low:1,high:3},
    {title:'r=4，加入數字 4',explanation:'sum=6+4=10，視窗 [1,4] 再次可行，長度 4 與目前 answer 相同。',lines:[3,4,5,6],state:{window:'[1,4]',sum:10,candidateLength:4},active:[1,4],muted:[0],low:1,high:4},
    {title:'移除 a[1] 後仍可行',explanation:'減去 1 後 sum=9、l=2。視窗 [2,4] 仍滿足 sum≥7，所以 while 不停止，還能繼續縮。',lines:[7,5],state:{removed:'a[1]=1',window:'[2,4]',sum:9},active:[1,2,4],muted:[0,1],low:2,high:4},
    {title:'找到更短的長度 3',explanation:'視窗 [2,4]=[3,2,4]，總和 9，長度只有 3。更新 answer=min(4,3)=3。',lines:[5,6],state:{window:'[2,4]',sum:9,answer:'4 → 3'},active:[2,4],accepted:[2,3,4],muted:[0,1],low:2,high:4},
    {title:'再縮一次會失效',explanation:'移除 a[2]=3 後 sum=6、l=3，已低於 7。這證明以 r=4 結尾的最短可行視窗長度就是 3。',lines:[7,8],state:{removed:'a[2]=3',window:'[3,4]',sum:6},active:[2],muted:[0,1,2],low:3,high:4},
    {title:'r=5，加入 1 再次達標',explanation:'視窗 [3,5]=[2,4,1] 的 sum=7，長度 3；answer 保持 3。',lines:[3,4,5,6],state:{window:'[3,5]',sum:7,answer:3},active:[3,5],accepted:[3,4,5],muted:[0,1,2],low:3,high:5},
    {title:'縮掉 2 後等待下一格',explanation:'移除 a[3]=2 後 sum=5、l=4，視窗暫時不可行，因此 r 繼續向右。',lines:[7,8],state:{removed:'a[3]=2',window:'[4,5]',sum:5},active:[3],muted:[0,1,2,3],low:4,high:5},
    {title:'r=6，最後一個視窗達標',explanation:'加入 a[6]=2 得 sum=7，視窗 [4,6]=[4,1,2] 長度也是 3，沒有刷新最佳答案。',lines:[3,4,5,6],state:{window:'[4,6]',sum:7,candidateLength:3},active:[4,6],accepted:[4,5,6],muted:[0,1,2,3],low:4,high:6},
    {title:'回傳最短長度 3',explanation:'掃描完成後 answer=3。r 只走 7 格，l 也只往右移；即使有巢狀 while，兩個指標總移動次數仍是 O(n)。',lines:[10],state:{result:3,proof:'each endpoint moves right at most n times',complexity:'O(n)'},accepted:[2,3,4],muted:[0,1,5,6],low:2,high:4},
  ]}),
  make({ id:'prefix-sum',index:'09',category:'ARRAY',categoryId:'search-sort',subcategory:'陣列技巧',title:'Prefix Sum',zhTitle:'前綴和',description:'預處理前綴累積值，將區間和化成兩次查表。',complexity:'Build O(n) · Query O(1)',accent:'#78d8ff',animationVersion:2,sources:[{label:'USACO',title:'USACO Guide · Introduction to Prefix Sums',url:'https://usaco.guide/silver/prefix-sums'}],values:[2,5,1,4,9,3],code:['vector<long long> prefix(n + 1, 0);','for (int i = 0; i < n; ++i)','  prefix[i+1] = prefix[i] + a[i];','','long long rangeSum(int l, int r) {','  return prefix[r+1] - prefix[l];','}'],phases:[
    {title:'把重複加法改成預先累積',explanation:'目標是快速回答區間和。先建立 prefix，之後每次查詢只需讀兩個累積值，不必重新走過整段陣列。',lines:[1],state:{input:'[2,5,1,4,9,3]',goal:'range sum in O(1)',prefixSize:'n+1'},low:0,high:5},
    {title:'prefix[0] 代表空前綴',explanation:'定義 prefix[i] 為前 i 個元素的總和，也就是 a[0..i-1]。前 0 個元素總和自然是 0。',lines:[1],state:{definition:'prefix[i] = sum of a[0..i-1]',prefix:['0'],current:'prefix[0]'},active:[0]},
    {title:'加入 a[0]=2',explanation:'i=0，prefix[1]=prefix[0]+a[0]=0+2=2。prefix[1] 現在代表前 1 個元素。',lines:[2,3],state:{i:0,formula:'prefix[1] = 0 + 2',prefix:['0','2']},active:[0],accepted:[0]},
    {title:'加入 a[1]=5',explanation:'prefix[2]=prefix[1]+a[1]=2+5=7，代表區間 a[0..1] 的總和。',lines:[2,3],state:{i:1,formula:'prefix[2] = 2 + 5',prefix:['0','2','7']},active:[1],accepted:[0,1]},
    {title:'加入 a[2]=1',explanation:'prefix[3]=7+1=8。每一步只沿用前一格，因此建表時每個元素只被處理一次。',lines:[2,3],state:{i:2,formula:'prefix[3] = 7 + 1',prefix:['0','2','7','8']},active:[2],accepted:[0,1,2]},
    {title:'加入 a[3]=4',explanation:'prefix[4]=8+4=12，表示 a[0]+a[1]+a[2]+a[3]。',lines:[2,3],state:{i:3,formula:'prefix[4] = 8 + 4',prefix:['0','2','7','8','12']},active:[3],accepted:[0,1,2,3]},
    {title:'加入 a[4]=9',explanation:'prefix[5]=12+9=21。稍後查詢右端 r=4 時，就會讀取這個 r+1 位置。',lines:[2,3],state:{i:4,formula:'prefix[5] = 12 + 9',prefix:['0','2','7','8','12','21']},active:[4],accepted:[0,1,2,3,4]},
    {title:'加入最後的 a[5]=3',explanation:'prefix[6]=21+3=24，建表完成：0、2、7、8、12、21、24。建表總成本 O(n)。',lines:[2,3],state:{i:5,formula:'prefix[6] = 21 + 3',prefix:['0','2','7','8','12','21','24']},active:[5],accepted:[0,1,2,3,4,5]},
    {title:'現在查詢閉區間 [1,4]',explanation:'要計算 5+1+4+9。因為 prefix 使用半開定義，右端 4 對應 prefix[r+1]=prefix[5]。',lines:[5],state:{query:'[1,4]',l:1,r:4,readRight:'prefix[5]'},active:[1,4],low:1,high:4},
    {title:'prefix[5] 先取到 21',explanation:'prefix[5]=21 包含索引 0 到 4；它涵蓋答案區間，但多算了左邊索引 0 的數字 2。',lines:[6],state:{prefixRight:21,contains:'a[0..4]',extra:'a[0]'},active:[0,4],accepted:[0,1,2,3,4],low:0,high:4},
    {title:'prefix[1] 精確代表多算部分',explanation:'prefix[l]=prefix[1]=2，恰好是查詢左端以前的 a[0..0]。把它減掉後只留下 a[1..4]。',lines:[6],state:{prefixLeft:2,removes:'a[0..0]',remaining:'a[1..4]'},active:[0,1],muted:[0],low:1,high:4},
    {title:'相減得到答案 19',explanation:'rangeSum(1,4)=prefix[5]-prefix[1]=21-2=19。每次查詢只做兩次查表與一次減法，所以是 O(1)。',lines:[6],state:{formula:'21 - 2',answer:19,queryComplexity:'O(1)'},active:[1,4],accepted:[1,2,3,4],muted:[0,5],low:1,high:4},
  ]}),
  make({ id:'difference-array',index:'10',category:'ARRAY',categoryId:'search-sort',subcategory:'陣列技巧',title:'Difference Array',zhTitle:'差分陣列',description:'用兩個端點事件表示一次區間加值。',complexity:'Update O(1) · Restore O(n)',accent:'#78d8ff',animationVersion:2,sources:[{label:'USACO',title:'Competitive Programmer’s Handbook · Difference Array',url:'https://usaco.guide/CPH.pdf'}],values:[3,3,3,3,3,3],code:['vector<int> diff(n + 1);','diff[0] = a[0];','for (int i = 1; i < n; ++i) diff[i] = a[i] - a[i-1];','void rangeAdd(int l, int r, int x) {','  diff[l] += x;','  diff[r+1] -= x;','}','for (int i = 1; i < n; ++i) diff[i] += diff[i-1];'],phases:[
    {title:'把區間加值改寫成兩個事件',explanation:'原陣列是六個 3，要讓索引 [1,4] 全部 +2。差分陣列會記錄「數值從哪裡開始改變、從哪裡恢復」。',lines:[1],state:{input:'[3,3,3,3,3,3]',update:'[1,4] += 2',goal:'two endpoint events'},low:1,high:4},
    {title:'定義 diff[0]',explanation:'第一格沒有前一個元素，因此直接令 diff[0]=a[0]=3。它是還原陣列時的起始值。',lines:[2],state:{formula:'diff[0] = a[0]',diff:['3']},active:[0]},
    {title:'diff[1] 記錄 3−3',explanation:'對 i≥1，diff[i]=a[i]−a[i−1]。因為 a[1] 與 a[0] 都是 3，所以 diff[1]=0。',lines:[3],state:{i:1,formula:'3 - 3 = 0',diff:['3','0']},active:[0,1]},
    {title:'完成原始差分陣列',explanation:'相鄰元素全部相同，後續差都是 0，因此 diff=[3,0,0,0,0,0]。它的前綴和正好還原原陣列。',lines:[3],state:{diff:['3','0','0','0','0','0'],invariant:'prefix(diff) = a'},accepted:[0,1,2,3,4,5]},
    {title:'在 l=1 放入 +2 事件',explanation:'執行 diff[l]+=2，使從索引 1 開始的所有前綴和值都增加 2；這就是區間加值的入口。',lines:[4,5],state:{l:1,event:'+2 starts here',diff:['3','2','0','0','0','0']},active:[1],low:1,high:4},
    {title:'在 r+1=5 放入 −2 事件',explanation:'若不抵銷，+2 會一路影響到陣列末端。執行 diff[5]−=2，讓效果在索引 5 開始消失。',lines:[6],state:{rPlusOne:5,event:'−2 stops effect',diff:['3','2','0','0','0','-2']},active:[5],low:1,high:4},
    {title:'一次更新只改兩格',explanation:'不論區間 [l,r] 多長，都只修改 diff[l] 與 diff[r+1]，所以單次 rangeAdd 是 O(1)。',lines:[4,5,6,7],state:{changedIndices:['1','5'],updateCost:'O(1)',diff:['3','2','0','0','0','-2']},active:[1,5],accepted:[1,5],low:1,high:4},
    {title:'從索引 0 開始還原',explanation:'還原就是對 diff 做前綴和。第一格保持 3，作為 running value。',lines:[8],state:{i:0,running:3,restored:['3']},active:[0],accepted:[0]},
    {title:'索引 1 吃到 +2 事件',explanation:'running=3+diff[1]=3+2=5，因此還原後 a[1]=5。+2 的影響從這一格正式開始。',lines:[8],state:{i:1,formula:'3 + 2 = 5',restored:['3','5']},active:[1],accepted:[0,1],low:1,high:1},
    {title:'索引 2 延續目前值',explanation:'diff[2]=0，所以 running 保持 5；a[2] 也被區間更新涵蓋。',lines:[8],state:{i:2,formula:'5 + 0 = 5',restored:['3','5','5']},active:[2],accepted:[0,1,2],low:1,high:2},
    {title:'索引 3 與 4 都延續為 5',explanation:'diff[3]、diff[4] 都是 0，running 不變。這正是用一個入口事件代表整段 +2 的效果。',lines:[8],state:{indices:'3,4',formula:'5 + 0 = 5',restored:['3','5','5','5','5']},active:[3,4],accepted:[0,1,2,3,4],low:1,high:4},
    {title:'索引 5 遇到抵銷事件',explanation:'running=5+diff[5]=5−2=3，所以區間外的 a[5] 恢復原值，更新精確停在 r=4。',lines:[8],state:{i:5,formula:'5 - 2 = 3',restored:['3','5','5','5','5','3']},active:[5],accepted:[0,1,2,3,4,5],low:1,high:4},
    {title:'得到更新後陣列',explanation:'最後結果是 [3,5,5,5,5,3]。大量區間更新可先各做 O(1) 事件，全部完成後只需一次 O(n) 還原。',lines:[8],state:{result:['3','5','5','5','5','3'],update:'O(1)',restore:'O(n)'},values:[3,5,5,5,5,3],accepted:[1,2,3,4],low:1,high:4},
  ]}),
  make({ id:'coordinate-compression',index:'11',category:'ARRAY',categoryId:'search-sort',subcategory:'陣列技巧',title:'Coordinate Compression',zhTitle:'離散化',description:'保留大小關係，將稀疏數值映射成緊密排名。',complexity:'O(n log n)',accent:'#78d8ff',animationVersion:2,sources:[{label:'你的模板',title:'Notion · 離散化',url:'https://app.notion.com/p/31b92ab76d4080c5bd99ea0b775eb1de'}],values:[100,5,1000000,5,42,900],code:['vector<int> values = a;','sort(values.begin(), values.end());','values.erase(unique(values.begin(), values.end()), values.end());','for (int& x : a)','  x = lower_bound(values.begin(), values.end(), x) - values.begin();'],phases:[
    {title:'先看出數值範圍太稀疏',explanation:'原值從 5 跳到 1,000,000，若直接以值當陣列索引會浪費大量空間。離散化只保留相對大小與相等關係。',lines:[1],state:{input:['100','5','1000000','5','42','900'],goal:'dense ranks',mustPreserve:'< and ==' },low:0,high:5},
    {title:'複製原陣列',explanation:'建立 values=a。原陣列的出現順序必須保留給最後映射，因此排序只在副本上進行。',lines:[1],state:{original:['100','5','1000000','5','42','900'],copy:['100','5','1000000','5','42','900']},accepted:[0,1,2,3,4,5]},
    {title:'排序副本',explanation:'排序後得到 [5,5,42,100,900,1000000]。相同值被放在一起，不同值則依大小排列。',lines:[2],state:{sorted:['5','5','42','100','900','1000000'],operation:'ascending sort'},values:[5,5,42,100,900,1000000],accepted:[0,1,2,3,4,5]},
    {title:'辨認重複的 5',explanation:'兩個 5 必須映射到相同 rank。unique 會把每組相等值壓成一個代表，而不是分配兩個排名。',lines:[3],state:{duplicate:5,rule:'equal values → equal rank',uniqueWrite:1},values:[5,5,42,100,900,1000000],active:[0,1]},
    {title:'unique 將不同值搬到前面',explanation:'unique 處理後，有效前綴是 [5,42,100,900,1000000]，並回傳這個前綴的結尾迭代器。',lines:[3],state:{validPrefix:['5','42','100','900','1000000'],discardedTail:'unspecified'},values:[5,42,100,900,1000000,5],accepted:[0,1,2,3,4],muted:[5]},
    {title:'erase 刪除無效尾端',explanation:'erase(unique(...), values.end()) 真正縮短 vector，得到嚴格遞增的查找表。',lines:[3],state:{values:['5','42','100','900','1000000'],size:'6 → 5',invariant:'strictly increasing'},values:[5,42,100,900,1000000],accepted:[0,1,2,3,4]},
    {title:'索引就是壓縮後排名',explanation:'查找表的索引 0、1、2、3、4 對應 5、42、100、900、1000000。值越小，rank 一定越小。',lines:[3],state:{table:['5→0','42→1','100→2','900→3','1000000→4'],rankRange:'[0,4]'},values:[5,42,100,900,1000000],accepted:[0,1,2,3,4]},
    {title:'映射原本的 100',explanation:'lower_bound 找到第一個不小於 100 的位置，也就是索引 2，因此原陣列第一格 100→2。',lines:[4,5],state:{originalValue:100,lowerBoundIndex:2,mapping:'100 → 2'},values:[2,5,1000000,5,42,900],active:[0],accepted:[0]},
    {title:'映射第一個 5',explanation:'5 在查找表的第一格，lower_bound 回傳索引 0，所以 5→0。',lines:[4,5],state:{originalValue:5,lowerBoundIndex:0,mapping:'5 → 0'},values:[2,0,1000000,5,42,900],active:[1],accepted:[0,1]},
    {title:'映射 1,000,000',explanation:'最大值位於查找表索引 4，因此 1000000→4；巨大數字現在只需小整數 4 表示。',lines:[4,5],state:{originalValue:1000000,lowerBoundIndex:4,mapping:'1000000 → 4'},values:[2,0,4,5,42,900],active:[2],accepted:[0,1,2]},
    {title:'相同的 5 得到相同 rank',explanation:'第四格再次遇到 5，lower_bound 仍回傳 0。接著 42→1、900→3，映射不受原出現順序影響。',lines:[4,5],state:{remaining:['5→0','42→1','900→3'],equality:'both 5s map to 0'},values:[2,0,4,0,1,3],active:[3,4,5],accepted:[0,1,2,3,4,5]},
    {title:'完成緊密且保序的排名',explanation:'結果是 [2,0,4,0,1,3]。例如 42<100，所以 1<2；兩個 5 都是 0。排序主導總成本 O(n log n)。',lines:[5],state:{result:['2','0','4','0','1','3'],preserved:'order and equality',complexity:'O(n log n)'},values:[2,0,4,0,1,3],accepted:[0,1,2,3,4,5]},
  ]}),
  make({ id:'kadane',index:'12',category:'ARRAY',categoryId:'search-sort',subcategory:'陣列技巧',title:"Kadane's Algorithm",zhTitle:'最大連續子陣列',description:'維護以當前位置結尾的最佳子陣列。',complexity:'O(n)',accent:'#78d8ff',animationVersion:2,sources:[{label:'USACO',title:'Competitive Programmer’s Handbook · Maximum Subarray Sum',url:'https://usaco.guide/CPH.pdf'}],values:[-2,3,-1,5,-6,4,2],code:['long long best = a[0], ending = a[0];','for (int i = 1; i < n; ++i) {','  ending = max<long long>(a[i], ending + a[i]);','  best = max(best, ending);','}','return best;'],phases:[
    {title:'把問題拆成兩個狀態',explanation:'ending 表示「一定以目前位置結尾」的最大連續和；best 表示所有已看過位置中的全域最大和。',lines:[1],state:{ending:'best sum ending at i',best:'best sum seen so far',goal:'maximum contiguous subarray'},low:0,high:6},
    {title:'用第一個元素初始化',explanation:'只有 a[0]=−2 時，唯一非空子陣列就是 [−2]，所以 ending=best=−2。這也能正確處理全負數陣列。',lines:[1],state:{i:0,ending:-2,best:-2},active:[0],accepted:[0],low:0,high:0},
    {title:'i=1：決定重開或延續',explanation:'以 3 結尾只有兩種合法選擇：單獨從 3 重開，或把 3 接在 ending=−2 後方得到 1。',lines:[2,3],state:{i:1,choices:['start: 3','extend: -2+3=1'],decision:'start new subarray'},active:[0,1],low:0,high:1},
    {title:'選 3，並更新全域最佳',explanation:'max(3,1)=3，所以 ending=3；best=max(−2,3)=3，目前最佳子陣列是 [3]。',lines:[3,4],state:{ending:'-2 → 3',best:'-2 → 3',range:'[1,1]'},active:[1],accepted:[1],muted:[0],low:1,high:1},
    {title:'i=2：把 −1 接在後面',explanation:'單獨 −1 與延續 3+(−1)=2 相比，延續較好，因此 ending=2；best 仍是 3。',lines:[2,3,4],state:{i:2,choices:['start: -1','extend: 3-1=2'],ending:2,best:3},active:[2],accepted:[1,2],muted:[0],low:1,high:2},
    {title:'i=3：延續後得到 7',explanation:'單獨 5 與延續 2+5=7 相比，選擇 7。ending 與 best 都更新為 7，最佳區間成為 [3,−1,5]。',lines:[2,3,4],state:{i:3,choices:['start: 5','extend: 2+5=7'],ending:7,best:7},active:[3],accepted:[1,2,3],muted:[0],low:1,high:3},
    {title:'i=4：負數使 ending 降到 1',explanation:'加入 −6 後延續值是 7−6=1，仍優於單獨 −6，所以 ending=1；但全域 best 保留 7，不會被較差狀態覆蓋。',lines:[2,3,4],state:{i:4,choices:['start: -6','extend: 7-6=1'],ending:1,best:7},active:[4],accepted:[1,2,3,4],muted:[0],low:1,high:4},
    {title:'i=5：正貢獻仍值得延續',explanation:'單獨 4 與延續 1+4=5 相比，前面累積的 1 仍有幫助，因此 ending=5；best 保持 7。',lines:[2,3,4],state:{i:5,choices:['start: 4','extend: 1+4=5'],ending:5,best:7},active:[5],accepted:[1,2,3,4,5],muted:[0],low:1,high:5},
    {title:'i=6：ending 再次來到 7',explanation:'延續 5+2=7 優於單獨 2，所以 ending=7。它追平 best，但沒有超過先前的最大值。',lines:[2,3,4],state:{i:6,choices:['start: 2','extend: 5+2=7'],ending:7,best:7},active:[6],accepted:[1,2,3,4,5,6],muted:[0],low:1,high:6},
    {title:'回傳最大連續和 7',explanation:'best=7，對應例如 [3,−1,5]。每個位置只比較「重開」與「延續」兩個選項，因此時間 O(n)、額外空間 O(1)。',lines:[5,6],state:{result:7,example:'[3,-1,5]',complexity:'O(n) time · O(1) space'},active:[1,3],accepted:[1,2,3],muted:[0,4,5,6],low:1,high:3},
  ]}),
  make({ id:'selection-sort',index:'13',category:'SORT',categoryId:'search-sort',subcategory:'排序與選擇',title:'Selection Sort',zhTitle:'選擇排序',description:'每輪找出未排序區最小值放到邊界。',complexity:'O(n²)',accent:'#78d8ff',animationVersion:2,sources:[{label:'USACO',title:'Principles of Algorithmic Problem Solving · Selection Sort',url:'https://usaco.guide/PAPS.pdf'}],values:array,code:['for (int i = 0; i < n; ++i) {','  int mn = i;','  for (int j = i+1; j < n; ++j)','    if (a[j] < a[mn]) mn = j;','  swap(a[i], a[mn]);','}'],phases:[
    {title:'建立「已排序前綴」不變量',explanation:'每輪開始時 [0,i) 已是最小的 i 個元素且順序正確；我們只在 [i,n) 找下一個最小值。',lines:[1],state:{input:['7','2','9','4','1','8','5','3'],sortedPrefix:'empty',unsorted:'[0,7]'},low:0,high:7},
    {title:'第 0 輪先假設 7 最小',explanation:'i=0，令 mn=0，暫時把 a[0]=7 當成未排序區最小值。接下來 j 從 1 掃到 7。',lines:[1,2,3],state:{i:0,mn:0,minValue:7,j:1},active:[0],low:0,high:7},
    {title:'比較 2 與目前最小值 7',explanation:'a[1]=2<7，條件成立，所以 mn 從 0 更新為 1。此時只記位置，還不交換。',lines:[3,4],state:{j:1,comparison:'2 < 7 → true',mn:'0 → 1'},active:[0,1],low:0,high:7},
    {title:'比較 9，不更新 mn',explanation:'a[2]=9 不小於目前的 a[mn]=2，因此 mn 保持 1，j 繼續向右。',lines:[3,4],state:{j:2,comparison:'9 < 2 → false',mn:1},active:[1,2],low:0,high:7},
    {title:'比較 4，不更新 mn',explanation:'a[3]=4 仍不小於 2，所以目前最小值仍是索引 1 的 2。',lines:[3,4],state:{j:3,comparison:'4 < 2 → false',mn:1},active:[1,3],low:0,high:7},
    {title:'遇到 1，更新最小位置',explanation:'a[4]=1<2，mn 更新成 4。現在 1 是已掃描區 [0,4] 中的最小值。',lines:[3,4],state:{j:4,comparison:'1 < 2 → true',mn:'1 → 4'},active:[1,4],low:0,high:7},
    {title:'比較 8，保留最小值 1',explanation:'a[5]=8 不小於 1，因此不更新 mn；目前索引 4 仍保存已掃描範圍內的最小元素。',lines:[3,4],state:{j:5,comparison:'8 < 1 → false',mn:4},active:[4,5],low:0,high:7},
    {title:'比較 5，保留最小值 1',explanation:'a[6]=5 不小於 1，mn 仍是 4；比較只淘汰候選，不會在掃描途中改動陣列位置。',lines:[3,4],state:{j:6,comparison:'5 < 1 → false',mn:4},active:[4,6],low:0,high:7},
    {title:'最後比較 3',explanation:'a[7]=3 也不小於 1。掃描完整個未排序區後，mn=4 已確定指向全域最小值。',lines:[3,4],state:{j:7,comparison:'3 < 1 → false',mn:4},active:[4,7],low:0,high:7},
    {title:'交換 7 與 1，固定第一格',explanation:'swap(a[0],a[4]) 後，1 被放到索引 0。它是全陣列最小值，因此這一格之後永遠不再改變。',lines:[5],state:{swap:'index 0 ↔ 4',sortedPrefix:['1']},values:[1,2,9,4,7,8,5,3],active:[0,4],accepted:[0],low:1,high:7},
    {title:'第 1 輪固定數字 2',explanation:'i=1，在 [1,7] 掃描後沒有值小於 2，因此 mn=1；自我交換後已排序前綴變成 [1,2]。',lines:[1,2,3,4,5],state:{i:1,mn:1,minValue:2,sortedPrefix:['1','2']},values:[1,2,9,4,7,8,5,3],active:[1],accepted:[0,1],low:2,high:7},
    {title:'第 2 輪找到最小值 3',explanation:'i=2 時從 [9,4,7,8,5,3] 找到索引 7 的 3，交換後 3 固定在索引 2。',lines:[1,2,3,4,5],state:{i:2,mn:7,swap:'9 ↔ 3'},values:[1,2,3,4,7,8,5,9],active:[2,7],accepted:[0,1,2],low:3,high:7},
    {title:'第 3 輪的 4 已在正確位置',explanation:'未排序區 [4,7,8,5,9] 的最小值就是 a[3]=4，所以 mn=i，不需實質移動。',lines:[1,2,3,4,5],state:{i:3,mn:3,swap:'self',sortedPrefix:['1','2','3','4']},values:[1,2,3,4,7,8,5,9],active:[3],accepted:[0,1,2,3],low:4,high:7},
    {title:'第 4 輪把 5 換到前面',explanation:'在 [7,8,5,9] 中最小值是索引 6 的 5；交換索引 4 與 6，固定第五個位置。',lines:[1,2,3,4,5],state:{i:4,mn:6,swap:'7 ↔ 5'},values:[1,2,3,4,5,8,7,9],active:[4,6],accepted:[0,1,2,3,4],low:5,high:7},
    {title:'第 5 輪把 7 換到索引 5',explanation:'未排序區 [8,7,9] 的最小值是 7。交換後前六格 [1,2,3,4,5,7] 全部固定。',lines:[1,2,3,4,5],state:{i:5,mn:6,swap:'8 ↔ 7'},values:[1,2,3,4,5,7,8,9],active:[5,6],accepted:[0,1,2,3,4,5],low:6,high:7},
    {title:'最後兩格已經有序',explanation:'i=6 時 8<9，mn=6；最後只剩 9，自然也正確。陣列完成排序。',lines:[1,2,3,4,5,6],state:{i:6,result:['1','2','3','4','5','7','8','9']},values:[1,2,3,4,5,7,8,9],accepted:[0,1,2,3,4,5,6,7],low:6,high:7},
    {title:'理解為什麼是 O(n²)',explanation:'比較次數是 (n−1)+(n−2)+…+1=n(n−1)/2；即使陣列原本已排序仍要掃描，所以時間 O(n²)。',lines:[1,3],state:{comparisons:'n(n-1)/2',swaps:'at most n',complexity:'O(n²)'},values:[1,2,3,4,5,7,8,9],accepted:[0,1,2,3,4,5,6,7]},
  ]}),
  make({ id:'bubble-sort',index:'14',category:'SORT',categoryId:'search-sort',subcategory:'排序與選擇',title:'Bubble Sort',zhTitle:'氣泡排序',description:'交換相鄰逆序對，讓最大值逐輪移到右端。',complexity:'O(n²)',accent:'#78d8ff',animationVersion:2,sources:[{label:'USACO',title:'USACO Guide · Introduction to Sorting',url:'https://usaco.guide/bronze/intro-sorting'}],values:[5,1,4,2,8],code:['for (int pass = 0; pass < n-1; ++pass)','  for (int j = 0; j+1 < n-pass; ++j)','    if (a[j] > a[j+1])','      swap(a[j], a[j+1]);'],phases:[
    {title:'每輪把最大值推向右端',explanation:'氣泡排序只比較相鄰元素。若左邊較大就交換；一輪掃到底後，未排序區最大值一定到最右側。',lines:[1],state:{input:['5','1','4','2','8'],invariant:'each pass fixes one suffix element',pass:0},low:0,high:4},
    {title:'比較 5 與 1',explanation:'pass=0、j=0。5>1 形成逆序對，若不交換就不可能得到遞增順序。',lines:[2,3],state:{pass:0,j:0,comparison:'5 > 1 → true'},active:[0,1],low:0,high:4},
    {title:'交換第一個逆序對',explanation:'swap 後變成 [1,5,4,2,8]。較大的 5 向右移一格，接著繼續和下一個鄰居比較。',lines:[4],state:{swap:'5 ↔ 1',movingValue:5},values:[1,5,4,2,8],active:[0,1],low:0,high:4},
    {title:'比較 5 與 4 並交換',explanation:'j=1 時 5>4，再次交換，陣列變成 [1,4,5,2,8]；5 繼續向右冒泡。',lines:[2,3,4],state:{pass:0,j:1,comparison:'5 > 4 → swap'},values:[1,4,5,2,8],active:[1,2],low:0,high:4},
    {title:'比較 5 與 2 並交換',explanation:'j=2 時 5>2，交換後得到 [1,4,2,5,8]。目前看過的最大值仍往右走。',lines:[2,3,4],state:{pass:0,j:2,comparison:'5 > 2 → swap'},values:[1,4,2,5,8],active:[2,3],low:0,high:4},
    {title:'比較 5 與 8，不交換',explanation:'j=3 時 5<8，順序正確。第一輪結束，索引 4 的 8 已確定是全陣列最大值。',lines:[2,3],state:{pass:0,j:3,comparison:'5 > 8 → false',fixed:8},values:[1,4,2,5,8],active:[3,4],accepted:[4],low:0,high:3},
    {title:'第二輪不再碰 8',explanation:'pass=1 時內圈只走到 n−pass−1；固定後綴 [8] 已正確，不需要重複比較。',lines:[1,2],state:{pass:1,fixedSuffix:['8'],activeRange:'[0,3]'},values:[1,4,2,5,8],accepted:[4],low:0,high:3},
    {title:'比較 1 與 4，不交換',explanation:'1<4，這一對已是遞增順序，不需要交換；直接讓 j 前進並保留目前的相對位置。',lines:[2,3],state:{pass:1,j:0,comparison:'1 > 4 → false'},values:[1,4,2,5,8],active:[0,1],accepted:[4],low:0,high:3},
    {title:'比較 4 與 2 並交換',explanation:'4>2 是逆序對，交換後得到 [1,2,4,5,8]；較大的 4 向本輪固定邊界再靠近一格。',lines:[2,3,4],state:{pass:1,j:1,comparison:'4 > 2 → swap'},values:[1,2,4,5,8],active:[1,2],accepted:[4],low:0,high:3},
    {title:'比較 4 與 5，固定第二大值',explanation:'4<5 不交換。第二輪完成後，未排序區最大值 5 固定在索引 3，固定後綴成為 [5,8]。',lines:[2,3],state:{pass:1,j:2,comparison:'4 > 5 → false',fixedSuffix:['5','8']},values:[1,2,4,5,8],active:[2,3],accepted:[3,4],low:0,high:2},
    {title:'第三輪比較 1 與 2',explanation:'pass=2，1<2，不交換。右側 [5,8] 完全不參與本輪。',lines:[1,2,3],state:{pass:2,j:0,comparison:'1 > 2 → false'},values:[1,2,4,5,8],active:[0,1],accepted:[3,4],low:0,high:2},
    {title:'比較 2 與 4，固定 4',explanation:'2<4 不交換。第三輪結束後 4 固定，現在後綴 [4,5,8] 已完成。',lines:[2,3],state:{pass:2,j:1,comparison:'2 > 4 → false',fixedSuffix:['4','5','8']},values:[1,2,4,5,8],active:[1,2],accepted:[2,3,4],low:0,high:1},
    {title:'最後比較 1 與 2',explanation:'pass=3 只剩一組相鄰元素。1<2，不需交換，兩格也確定有序。',lines:[1,2,3],state:{pass:3,j:0,comparison:'1 > 2 → false'},values:[1,2,4,5,8],active:[0,1],accepted:[0,1,2,3,4],low:0,high:1},
    {title:'排序完成並計算成本',explanation:'結果是 [1,2,4,5,8]。比較次數為 (n−1)+…+1，所以基本版本即使接近有序仍是 O(n²)。',lines:[1,2],state:{result:['1','2','4','5','8'],comparisons:'n(n-1)/2',complexity:'O(n²)'},values:[1,2,4,5,8],accepted:[0,1,2,3,4]},
  ]}),
  make({ id:'merge-sort',index:'15',category:'SORT',categoryId:'search-sort',subcategory:'排序與選擇',title:'Merge Sort',zhTitle:'合併排序',description:'遞迴排序兩半，再線性合併兩個有序序列。',complexity:'O(n log n)',accent:'#78d8ff',animationVersion:2,sources:[{label:'你的教材',title:'CPPBook · Divide and Conquer / Merge Sort',url:'https://pingchungchang.github.io/CPPBook/lectures/dc/'}],values:[7,2,9,4,1,8,5,3],code:['void mergeSort(int l, int r) {','  if (r-l <= 1) return;','  int m = (l+r)/2;','  mergeSort(l,m); mergeSort(m,r);','  inplace_merge(a.begin()+l, a.begin()+m, a.begin()+r);','  // a[l..r) is now sorted','}'],phases:[
    {title:'用半開區間表示問題',explanation:'mergeSort(0,8) 負責索引 [0,8)。半開寫法讓長度直接等於 r−l，也方便把中點切成不重疊兩半。',lines:[1],state:{call:'mergeSort(0,8)',range:'[0,8)',length:8},low:0,high:7},
    {title:'第一次切成左右各四格',explanation:'m=(0+8)/2=4，問題分成 [0,4) 與 [4,8)。兩半排序完成後才會合併。',lines:[2,3,4],state:{mid:4,split:'[0,4) + [4,8)',depth:1},active:[3,4],low:0,high:7},
    {title:'左半再切成兩格',explanation:'mergeSort(0,4) 計算 m=2，分成 [0,2)=[7,2] 與 [2,4)=[9,4]。',lines:[2,3,4],state:{call:'mergeSort(0,4)',mid:2,split:'[0,2) + [2,4)'},active:[1,2],low:0,high:3},
    {title:'[7,2] 切到單元素',explanation:'[0,2) 再切成 [0,1) 與 [1,2)。兩段長度都是 1，觸發 base case，單元素天然有序。',lines:[2,3,4],state:{split:'[7] + [2]',baseCases:2},active:[0,1],low:0,high:1},
    {title:'合併 [7] 與 [2]',explanation:'比較兩邊首端 7 與 2，先取 2，再把剩下的 7 接上，寫回得到 [2,7]。',lines:[5,6],state:{left:['7'],right:['2'],buffer:['2','7']},values:[2,7,9,4,1,8,5,3],active:[0,1],accepted:[0,1],low:0,high:1},
    {title:'[9,4] 也切到單元素',explanation:'[2,4) 分成 [9] 與 [4]，兩者各自已排序，準備合併。',lines:[2,3,4],state:{split:'[9] + [4]',baseCases:2},values:[2,7,9,4,1,8,5,3],active:[2,3],accepted:[0,1],low:2,high:3},
    {title:'合併得到 [4,9]',explanation:'比較 9 與 4，先放 4，再放 9；左半目前成為兩個有序段 [2,7] 與 [4,9]。',lines:[5,6],state:{left:['9'],right:['4'],buffer:['4','9']},values:[2,7,4,9,1,8,5,3],active:[2,3],accepted:[0,1,2,3],low:2,high:3},
    {title:'合併左半的兩個有序段',explanation:'依序比較首端：2<4 取 2、4<7 取 4、7<9 取 7，最後接上 9，得到 [2,4,7,9]。',lines:[5,6],state:{left:['2','7'],right:['4','9'],buffer:['2','4','7','9']},values:[2,4,7,9,1,8,5,3],active:[0,1,2,3],accepted:[0,1,2,3],low:0,high:3},
    {title:'開始處理右半 [1,8,5,3]',explanation:'遞迴回到 mergeSort(4,8)，以 m=6 分成 [1,8] 與 [5,3]。',lines:[3,4],state:{call:'mergeSort(4,8)',mid:6,split:'[4,6) + [6,8)'},values:[2,4,7,9,1,8,5,3],active:[5,6],accepted:[0,1,2,3],low:4,high:7},
    {title:'[1,8] 切開後原本就有序',explanation:'兩個單元素 1 與 8 合併時先取 1 再取 8，結果仍是 [1,8]。',lines:[2,3,4,5,6],state:{left:['1'],right:['8'],buffer:['1','8']},values:[2,4,7,9,1,8,5,3],active:[4,5],accepted:[0,1,2,3,4,5],low:4,high:5},
    {title:'[5,3] 合併成 [3,5]',explanation:'比較 5 與 3，先取較小的 3，再接上剩餘的 5；最後把 buffer 寫回右端兩格。',lines:[2,3,4,5,6],state:{left:['5'],right:['3'],buffer:['3','5']},values:[2,4,7,9,1,8,3,5],active:[6,7],accepted:[0,1,2,3,4,5,6,7],low:6,high:7},
    {title:'合併右半得到 [1,3,5,8]',explanation:'合併 [1,8] 與 [3,5]：依序取 1、3、5，最後接 8。右半完成排序。',lines:[5,6],state:{left:['1','8'],right:['3','5'],buffer:['1','3','5','8']},values:[2,4,7,9,1,3,5,8],active:[4,5,6,7],accepted:[0,1,2,3,4,5,6,7],low:4,high:7},
    {title:'最終合併：先比較 2 與 1',explanation:'左右為 [2,4,7,9] 與 [1,3,5,8]。首端 1 較小，先寫入 buffer。',lines:[5],state:{leftFront:2,rightFront:1,take:1,buffer:['1']},values:[2,4,7,9,1,3,5,8],active:[0,4],low:0,high:7},
    {title:'接著取左邊的 2',explanation:'右指標移到 3，現在比較 2 與 3；2 較小，buffer 變成 [1,2]。',lines:[5],state:{leftFront:2,rightFront:3,take:2,buffer:['1','2']},values:[2,4,7,9,1,3,5,8],active:[0,5],low:0,high:7},
    {title:'比較 4 與 3，取 3',explanation:'3 較小，從右半取出。左右各自未取出的部分仍然保持有序。',lines:[5],state:{leftFront:4,rightFront:3,take:3,buffer:['1','2','3']},values:[2,4,7,9,1,3,5,8],active:[1,5],low:0,high:7},
    {title:'比較 4 與 5，取 4',explanation:'4 較小，buffer 成為 [1,2,3,4]。每次只需比較兩個首端，不必回頭。',lines:[5],state:{leftFront:4,rightFront:5,take:4,buffer:['1','2','3','4']},values:[2,4,7,9,1,3,5,8],active:[1,6],low:0,high:7},
    {title:'比較 7 與 5，取 5',explanation:'5 較小，buffer 變成 [1,2,3,4,5]；右半下一個首端是 8。',lines:[5],state:{leftFront:7,rightFront:5,take:5,buffer:['1','2','3','4','5']},values:[2,4,7,9,1,3,5,8],active:[2,6],low:0,high:7},
    {title:'比較 7 與 8，取 7',explanation:'7 較小，buffer 加入 7；左半只剩 9，右半只剩 8。',lines:[5],state:{leftFront:7,rightFront:8,take:7,buffer:['1','2','3','4','5','7']},values:[2,4,7,9,1,3,5,8],active:[2,7],low:0,high:7},
    {title:'取 8，再接上剩餘的 9',explanation:'8<9，先取 8；右半耗盡後，把左半剩餘的 9 直接接到 buffer 尾端。',lines:[5],state:{takeOrder:['8','9'],buffer:['1','2','3','4','5','7','8','9']},values:[2,4,7,9,1,3,5,8],active:[3,7],low:0,high:7},
    {title:'寫回並完成穩定排序',explanation:'把 buffer 寫回 a[0..8)，得到 [1,2,3,4,5,7,8,9]。每層 O(n)、共 O(log n) 層，總計 O(n log n)。',lines:[6,7],state:{result:['1','2','3','4','5','7','8','9'],stable:'yes',complexity:'O(n log n)'},values:[1,2,3,4,5,7,8,9],accepted:[0,1,2,3,4,5,6,7]},
  ]}),
  make({ id:'quick-sort',index:'16',category:'SORT',categoryId:'search-sort',subcategory:'排序與選擇',title:'Quick Sort',zhTitle:'快速排序',description:'以 pivot 分割，小值放左、大值放右後遞迴。',complexity:'Average O(n log n)',accent:'#78d8ff',animationVersion:2,sources:[{label:'USACO',title:'USACO Guide · Introduction to Sorting',url:'https://usaco.guide/bronze/intro-sorting'}],values:[7,2,9,4,1,8,5,3],code:['void quickSort(int l, int r) {','  if (l >= r) return;','  int pivot = a[r], store = l;','  for (int j = l; j < r; ++j) {','    if (a[j] <= pivot)','      swap(a[store++], a[j]);','  }','  swap(a[store], a[r]);','  quickSort(l, store-1);','  quickSort(store+1, r);','}'],phases:[
    {title:'對整段 [0,7] 呼叫 Quick Sort',explanation:'目前要排序八個元素。只要 l<r，就選一個 pivot 做 partition，再分別處理 pivot 左右兩段。',lines:[1,2],state:{call:'quickSort(0,7)',range:'[0,7]',goal:'partition then recurse'},low:0,high:7},
    {title:'選最後元素 3 當 Pivot',explanation:'pivot=a[7]=3，store=0。掃描不變量是 [l,store) 全部 ≤pivot，而 [store,j) 全部 >pivot。',lines:[3],state:{pivot:3,store:0,j:0,invariant:'[l,store) ≤ pivot; [store,j) > pivot'},active:[7],low:0,high:7},
    {title:'j=0：7 大於 Pivot',explanation:'a[0]=7>3，不應進入小值區，因此不交換，store 仍停在 0；j 繼續右移。',lines:[4,5],state:{j:0,comparison:'7 ≤ 3 → false',store:0},active:[0,7],low:0,high:7},
    {title:'j=1：2 進入小值區',explanation:'2≤3，交換 a[store=0] 與 a[1]，得到 [2,7,9,4,1,8,5,3]，再把 store 增加為 1。',lines:[4,5,6],state:{j:1,comparison:'2 ≤ 3 → true',store:'0 → 1'},values:[2,7,9,4,1,8,5,3],active:[0,1,7],low:0,high:7},
    {title:'j=2：9 留在大值區',explanation:'9>3，條件為假，不交換。索引 [store=1,j=2] 仍屬於大於 pivot 的暫存區。',lines:[4,5],state:{j:2,comparison:'9 ≤ 3 → false',store:1},values:[2,7,9,4,1,8,5,3],active:[1,2,7],low:0,high:7},
    {title:'j=3：4 也大於 Pivot',explanation:'4>3，所以 store 保持 1。掃描只分類元素，pivot 仍留在最右端。',lines:[4,5],state:{j:3,comparison:'4 ≤ 3 → false',store:1},values:[2,7,9,4,1,8,5,3],active:[1,3,7],low:0,high:7},
    {title:'j=4：把 1 交換進小值區',explanation:'1≤3，交換 a[1]=7 與 a[4]=1，得到 [2,1,9,4,7,8,5,3]，store 前進到 2。',lines:[4,5,6],state:{j:4,comparison:'1 ≤ 3 → true',store:'1 → 2'},values:[2,1,9,4,7,8,5,3],active:[1,4,7],accepted:[0,1],low:0,high:7},
    {title:'j=5：8 留在右區',explanation:'8>3，不進行交換。小值區 [2,1] 保持不變，store=2 指向 pivot 最後應放的位置。',lines:[4,5],state:{j:5,comparison:'8 ≤ 3 → false',store:2},values:[2,1,9,4,7,8,5,3],active:[2,5,7],accepted:[0,1],low:0,high:7},
    {title:'j=6：5 仍大於 Pivot',explanation:'最後一個待掃描值 5>3，store 仍是 2。現在 [0,2) 全部≤3，[2,7) 全部>3。',lines:[4,5,7],state:{j:6,comparison:'5 ≤ 3 → false',store:2},values:[2,1,9,4,7,8,5,3],active:[2,6,7],accepted:[0,1],low:0,high:7},
    {title:'把 Pivot 交換到 store=2',explanation:'交換 a[2]=9 與 a[7]=3，得到 [2,1,3,4,7,8,5,9]。3 左邊都較小、右邊都較大，因此索引 2 永久固定。',lines:[8],state:{swap:'a[2] ↔ a[7]',pivotFinalIndex:2},values:[2,1,3,4,7,8,5,9],active:[2,7],accepted:[2],low:0,high:7},
    {title:'遞迴處理左段 [2,1]',explanation:'呼叫 quickSort(0,1)，選 pivot=1。掃描 2>1 後把 1 換到前面，左段成為 [1,2]。',lines:[9,3,4,5,8],state:{call:'quickSort(0,1)',pivot:1,result:['1','2']},values:[1,2,3,4,7,8,5,9],active:[0,1],accepted:[0,1,2],low:0,high:1},
    {title:'遞迴處理 Pivot 右段',explanation:'接著呼叫 quickSort(3,7) 處理 [4,7,8,5,9]；已固定的索引 0 到 2 不再參與。',lines:[10,1,2],state:{call:'quickSort(3,7)',range:'[3,7]',fixedPrefix:['1','2','3']},values:[1,2,3,4,7,8,5,9],accepted:[0,1,2],low:3,high:7},
    {title:'Pivot 9 已是右段最大值',explanation:'右段選 pivot=9，所有 4、7、8、5 都≤9，因此 store 一路走到 7，pivot 自我交換並固定。',lines:[3,4,5,6,8],state:{pivot:9,store:7,partition:'all values ≤ 9'},values:[1,2,3,4,7,8,5,9],active:[7],accepted:[0,1,2,7],low:3,high:7},
    {title:'以 Pivot 5 分割 [4,7,8,5]',explanation:'在 [3,6] 選 pivot=5。4≤5 留左邊，7 與 8 留右邊，pivot 歸位後得到 [4,5,8,7]。',lines:[3,4,5,6,8],state:{call:'quickSort(3,6)',pivot:5,pivotFinalIndex:4},values:[1,2,3,4,5,8,7,9],active:[3,4,6],accepted:[0,1,2,4,7],low:3,high:6},
    {title:'最後把 [8,7] 排成 [7,8]',explanation:'遞迴到 [5,6]，pivot=7；8>7，所以 pivot 與 8 交換。所有長度 1 的子段接著觸發 base case。',lines:[2,3,4,5,8,9,10],state:{call:'quickSort(5,6)',pivot:7,result:['7','8']},values:[1,2,3,4,5,7,8,9],active:[5,6],accepted:[0,1,2,3,4,5,6,7],low:5,high:6},
    {title:'排序完成並理解複雜度',explanation:'結果為 [1,2,3,4,5,7,8,9]。平衡分割平均 O(n log n)；若 pivot 每次都最極端，最壞會退化成 O(n²)。',lines:[1,2,9,10,11],state:{result:['1','2','3','4','5','7','8','9'],average:'O(n log n)',worst:'O(n²)'},values:[1,2,3,4,5,7,8,9],accepted:[0,1,2,3,4,5,6,7]},
  ]}),
  make({ id:'quickselect',index:'17',category:'SELECT',categoryId:'search-sort',subcategory:'排序與選擇',title:'Quickselect',zhTitle:'第 k 小元素',description:'只遞迴包含第 k 名的 partition 一側。',complexity:'Expected O(n)',accent:'#78d8ff',values:[7,2,9,4,1,8,5,3],code:['int quickselect(int l, int r, int k) {','  int p = partition(l, r);','  if (p == k) return a[p];','  if (k < p) return quickselect(l,p-1,k);','  return quickselect(p+1,r,k);','}'],phases:[
    {title:'Partition 固定 Pivot 排名',explanation:'partition 後 pivot 的位置 p 就是它在整體排序中的最終排名；不需要把其他元素完全排序。',lines:[1,2],state:{k:3,pivot:4,p:3},active:[3]},
    {title:'只保留包含 k 的一側',explanation:'若 k<p，第 k 小必在左側；若 k>p 必在右側。另一側可永久捨棄，因此期望工作量形成 n+n/2+…。',lines:[3,4,5],state:{k:3,p:5,decision:'search left'},muted:[6,7],low:0,high:5},
    {title:'Pivot 命中 k',explanation:'當 p=k 時，a[p] 前方恰有 k 個不大於它的元素，因此直接回傳，不必排序左右兩側。',lines:[3],state:{k:3,p:3,result:4},values:[1,2,3,4,9,8,5,7],active:[3],accepted:[3]},
  ]}),
  make({ id:'stack',index:'18',category:'STACK',categoryId:'linear-structures',subcategory:'Stack',title:'Stack',zhTitle:'堆疊',description:'後進先出，只操作同一端的資料結構。',complexity:'Push/Pop O(1)',accent:'#62e4d0',values:[2,5,1,4],code:['stack<int> st;','st.push(2);','st.push(5);','int top = st.top();','st.pop();'],phases:[
    {title:'Push 到頂端',explanation:'Stack 維持 LIFO：新元素只加入 top。底下元素不移動，因此 push 為 O(1)。',lines:[1,2,3],state:{stack:['2','5'],top:5},active:[1]},
    {title:'Top 只讀取頂端',explanation:'top() 回傳最後加入且尚未移除的元素 5，不改變 stack 內容。',lines:[4],state:{stack:['2','5'],returned:5},active:[1]},
    {title:'Pop 移除頂端',explanation:'pop() 移除 5 後，2 成為新的 top。空 stack 不可呼叫 top 或 pop。',lines:[5],state:{stack:['2'],top:2},values:[2],accepted:[0]},
  ]}),
  make({ id:'parentheses-matching',index:'19',category:'STACK',categoryId:'linear-structures',subcategory:'Stack',title:'Parentheses Matching',zhTitle:'括號匹配',description:'用 Stack 保存尚未配對的左括號。',complexity:'O(n)',accent:'#62e4d0',values:[1,2,3,4,5,6],code:['for (char c : s) {','  if (isOpen(c)) st.push(c);','  else {','    if (st.empty() || !match(st.top(), c)) return false;','    st.pop();','  }','}','return st.empty();'],phases:[
    {title:'左括號入 Stack',explanation:'讀到左括號時尚不知道它與誰配對，因此依出現順序壓入；最內層括號位於 top。',lines:[1,2],state:{input:'([{}])',stack:['(','[','{']},active:[2]},
    {title:'右括號必須匹配 Top',explanation:'巢狀結構要求最晚出現的左括號最先閉合；若右括號與 top 類型不同，序列立即非法。',lines:[3,4],state:{current:'}',top:'{',match:'true'},active:[3]},
    {title:'全部讀完還必須為空',explanation:'每次成功配對就 pop。結尾 stack 為空代表沒有未閉合左括號，整串才合法。',lines:[5,8],state:{stack:[],result:'valid'},accepted:[0,1,2,3,4,5]},
  ]}),
  make({ id:'monotonic-stack',index:'20',category:'STACK',categoryId:'linear-structures',subcategory:'Stack',title:'Monotonic Stack',zhTitle:'單調堆疊',description:'移除永遠不可能再成為答案的候選元素。',complexity:'O(n)',accent:'#62e4d0',values:[2,1,5,3,4,7],code:['for (int x : a) {','  while (!st.empty() && st.top() <= x)','    st.pop();','  st.push(x);','}'],phases:[
    {title:'維持嚴格遞減 Stack',explanation:'Stack 從底到頂遞減。新值 5 到來時，top=1≤5；1 被 5 支配，對未來查詢不會比 5 更有用。',lines:[1,2,3],state:{stack:['2','1'],incoming:5,decision:'pop 1'},active:[1,2]},
    {title:'持續移除被支配候選',explanation:'接著 2≤5 也被 pop。每個元素最多 push 一次、pop 一次，所以巢狀 while 的總成本仍為 O(n)。',lines:[2,3],state:{stack:['2'],incoming:5,decision:'pop 2'},active:[0,2],muted:[1]},
    {title:'Push 新候選',explanation:'移除所有不大於 5 的元素後 push 5，恢復嚴格遞減不變量。',lines:[4],state:{stack:['5','3'],incoming:4},active:[2,3,4],accepted:[2]},
  ]}),
  make({ id:'next-greater-element',index:'21',category:'STACK',categoryId:'linear-structures',subcategory:'Stack',title:'Next Greater Element',zhTitle:'右側第一個更大元素',description:'用索引 Stack 等待右側第一個更大值。',complexity:'O(n)',accent:'#62e4d0',values:[2,1,5,3,4],code:['for (int i = 0; i < n; ++i) {','  while (!st.empty() && a[st.top()] < a[i]) {','    answer[st.top()] = a[i];','    st.pop();','  }','  st.push(i);','}'],phases:[
    {title:'未找到答案的索引入 Stack',explanation:'Stack 保存尚未遇到右側更大值的索引。2、1 尚無答案，依序等待。',lines:[1,6],state:{stack:['0(2)','1(1)'],answers:['?','?']},active:[0,1]},
    {title:'新值解決所有較小 Top',explanation:'5 到來時，1 與 2 都小於 5；因為中間沒有更大值，5 正是它們各自第一個右側更大元素。',lines:[2,3,4],state:{incoming:5,resolved:['NGE[1]=5','NGE[0]=5']},active:[0,1,2],accepted:[0,1]},
    {title:'剩餘索引沒有右側更大值',explanation:'掃描結束後仍在 Stack 的索引答案為 -1。每個索引只進出 Stack 一次。',lines:[6],state:{stack:['2(5)','4(4)'],answers:['5','5','-1','4','-1']},accepted:[0,1,2,3,4]},
  ]}),
  make({ id:'queue',index:'22',category:'QUEUE',categoryId:'linear-structures',subcategory:'Queue 與 Deque',title:'Queue',zhTitle:'佇列',description:'先進先出，尾端加入、前端移除。',complexity:'Push/Pop O(1)',accent:'#62e4d0',values:[2,5,1,4],code:['queue<int> q;','q.push(2);','q.push(5);','int first = q.front();','q.pop();'],phases:[
    {title:'從 Back 入隊',explanation:'新元素 2、5 依序加入尾端；先加入的 2 保持在 front。',lines:[1,2,3],state:{front:2,queue:['2','5'],back:5},active:[1]},
    {title:'Front 取得最早元素',explanation:'FIFO 規則保證 front() 回傳等待最久的 2，但不改變 queue。',lines:[4],state:{returned:2,queue:['2','5']},active:[0]},
    {title:'從 Front 出隊',explanation:'pop() 移除 2 後，5 成為新的 front。Queue 適合按到達順序處理事件。',lines:[5],state:{queue:['5'],front:5},values:[5],accepted:[0]},
  ]}),
  make({ id:'deque',index:'23',category:'QUEUE',categoryId:'linear-structures',subcategory:'Queue 與 Deque',title:'Deque',zhTitle:'雙端佇列',description:'兩端皆可 O(1) 加入與移除。',complexity:'O(1) per end operation',accent:'#62e4d0',values:[2,5,1,4],code:['deque<int> dq;','dq.push_back(5);','dq.push_front(2);','dq.pop_back();','dq.pop_front();'],phases:[
    {title:'尾端加入',explanation:'push_back 將 5 放到右端，不影響左端位置；既有元素順序保持不變，因此 front 仍指向最早的元素。',lines:[1,2],state:{deque:['5'],front:5,back:5},active:[0]},
    {title:'前端加入',explanation:'push_front 將 2 放到左端；Deque 同時保留兩個可操作邊界。',lines:[3],state:{deque:['2','5'],front:2,back:5},active:[0,1]},
    {title:'依需求從任一端移除',explanation:'pop_back 移除 5；pop_front 則會移除 2。底層分段儲存使兩端操作維持攤銷 O(1)。',lines:[4,5],state:{operation:'pop_back',deque:['2']},values:[2],accepted:[0]},
  ]}),
  make({ id:'binary-heap',index:'24',category:'HEAP',categoryId:'linear-structures',subcategory:'Heap',title:'Binary Heap',zhTitle:'二元堆積',description:'以完全二元樹維持父節點不大於子節點。',complexity:'Push/Pop O(log n)',accent:'#62e4d0',values:[2,5,3,9,8,7],code:['priority_queue<int, vector<int>, greater<int>> pq;','pq.push(x); // append then sift up','int minimum = pq.top();','pq.pop(); // move last to root, sift down'],phases:[
    {title:'陣列表示完全二元樹',explanation:'索引 i 的子節點為 2i+1、2i+2。Min-heap 只保證父≤子，不保證整個陣列排序。',lines:[1],state:{heap:['2','5','3','9','8','7'],minimum:2},accepted:[0]},
    {title:'Push 後向上修復',explanation:'新值先放陣列尾端；若小於父節點就交換，直到到達根或父≤子，路徑長最多為樹高 O(log n)。',lines:[2],state:{incoming:1,path:['index 6','parent 2','root 0']},values:[1,5,2,9,8,7,3],active:[0,2,6]},
    {title:'Pop Root 後向下修復',explanation:'移除最小值後把最後元素放到 root，再與較小子節點交換，恢復 heap invariant。',lines:[3,4],state:{removed:1,newMinimum:2},values:[2,5,3,9,8,7],accepted:[0]},
  ]}),
  make({ id:'monotonic-queue',index:'25',category:'QUEUE',categoryId:'linear-structures',subcategory:'Queue 與 Deque',title:'Monotonic Queue',zhTitle:'單調佇列',description:'Deque 同時移除過期索引與被支配候選。',complexity:'O(n)',accent:'#62e4d0',values:[1,3,-1,-3,5,3,6,7],code:['for (int i = 0; i < n; ++i) {','  while (!dq.empty() && dq.front() <= i-k) dq.pop_front();','  while (!dq.empty() && a[dq.back()] <= a[i]) dq.pop_back();','  dq.push_back(i);','  if (i >= k-1) answer.push_back(a[dq.front()]);','}'],phases:[
    {title:'移除已離開視窗的索引',explanation:'Deque 儲存索引。front≤i-k 代表該元素不在目前長度 k 視窗內，必須先從前端移除。',lines:[1,2],state:{i:3,k:3,expired:0,deque:['1(3)','2(-1)']},active:[0,3],low:1,high:3},
    {title:'從尾端移除被支配值',explanation:'新值 5 大於尾端所有候選；它更大且更晚過期，因此那些候選不可能成為任何未來視窗最大值。',lines:[3],state:{incoming:5,popped:['-3','-1','3'],deque:[]},active:[1,2,3,4],low:2,high:4},
    {title:'Front 永遠是視窗最大值',explanation:'維持索引遞增、值遞減後，front 對應當前視窗最大值。每個索引最多進出一次，總成本 O(n)。',lines:[4,5],state:{deque:['6(6)','5(3)'],windowMax:6},active:[5,6],accepted:[6],low:4,high:6},
  ]}),
]
