import type { AlgorithmLesson, Frame } from './algorithms'
import { eventFrame } from './traceAuthoring'

type TraceBuilder=(lesson:AlgorithmLesson)=>Frame[]

const middleView=(step:number):NonNullable<Frame['executionView']> => {
  const sums=[[0,3,5,8],[0,6,7,13]]
  const active=step===3?['0,3','1,3','2,3','3,3']:step===4?['0,1']:step===5?['1,1']:step>=6?['2,1','2,3']:[]
  return {kind:'table',title:'MEET IN THE MIDDLE · 2² subset sums per half',
    columns:['left mask','left sum','right mask','right sum'],
    rows:[0,1,2,3].map((mask)=>[mask.toString(2).padStart(2,'0'),step>=1?String(sums[0][mask]):'—',mask.toString(2).padStart(2,'0'),step>=2?String(sums[1][mask]):'—']),
    activeCells:active,
    badges:['left=[3,5] · right=[6,7]','target=12',...(step===3?['right sums sorted']:step===4?['x=0 · need=12 · miss']:step===5?['x=3 · need=9 · miss']:step>=6?['x=5 · need=7 · match']:[])],
  }
}

const parserTokens=['3','+','4','*','(','2','-','1',')']
const expressionSnapshots=[
  {values:[],ops:[]},
  {values:['3'],ops:[]},
  {values:['3'],ops:['+']},
  {values:['3','4'],ops:['+']},
  {values:['3','4'],ops:['+','*']},
  {values:['3','4'],ops:['+','*','(']},
  {values:['3','4','2'],ops:['+','*','(']},
  {values:['3','4','2'],ops:['+','*','(','-']},
  {values:['3','4','2','1'],ops:['+','*','(','-']},
  {values:['3','4','1'],ops:['+','*','(']},
  {values:['3','4','1'],ops:['+','*']},
  {values:['3','4','1'],ops:['+','*']},
  {values:['3','4'],ops:['+']},
  {values:['7'],ops:[]},
  {values:['7'],ops:[]},
]
const expressionView=(step:number):NonNullable<Frame['executionView']>=>{
  const snap=expressionSnapshots[Math.min(step,expressionSnapshots.length-1)]
  return {kind:'table',title:'EXPRESSION EVALUATION · 3 + 4 * (2 - 1)',
    columns:['token index','token','status'],
    rows:parserTokens.map((token,index)=>[String(index),token,index<Math.min(step,9)?'已讀':index===Math.min(step,8)?'目前':'待讀']),
    activeCells:step>=1&&step<=9?[(Math.min(step-1,8))+',1']:[],
    badges:['values = ['+snap.values.join(', ')+']','ops = ['+snap.ops.join(', ')+']',...(step>=13?['result = 7']:[])],
  }
}
const shuntingSnapshots=[
  {output:[],ops:[]},
  {output:['3'],ops:[]},
  {output:['3'],ops:['+']},
  {output:['3','4'],ops:['+']},
  {output:['3','4'],ops:['+','*']},
  {output:['3','4'],ops:['+','*','(']},
  {output:['3','4','2'],ops:['+','*','(']},
  {output:['3','4','2'],ops:['+','*','(','-']},
  {output:['3','4','2','1'],ops:['+','*','(','-']},
  {output:['3','4','2','1','-'],ops:['+','*','(']},
  {output:['3','4','2','1','-'],ops:['+','*']},
  {output:['3','4','2','1','-','*'],ops:['+']},
  {output:['3','4','2','1','-','*','+'],ops:[]},
  {output:['3','4','2','1','-','*','+'],ops:[]},
]
const shuntingView=(step:number):NonNullable<Frame['executionView']>=>{
  const snap=shuntingSnapshots[Math.min(step,shuntingSnapshots.length-1)]
  return {kind:'table',title:'SHUNTING YARD · 3 + 4 * (2 - 1)',
    columns:['token index','token','status'],
    rows:parserTokens.map((token,index)=>[String(index),token,index<Math.min(step,9)?'已讀':index===Math.min(step,8)?'目前':'待讀']),
    activeCells:step>=1&&step<=9?[(Math.min(step-1,8))+',1']:[],
    badges:['output = ['+snap.output.join(', ')+']','ops = ['+snap.ops.join(', ')+']',...(step>=13?['postfix = 3 4 2 1 - * +']:[])],
  }
}

const codeOverrides:Record<string,string[]>={
  'meet-in-the-middle':[
    'bool hasSubsetSumTarget(const vector<long long>& a,long long target){',
    '  int n=(int)a.size();',
    '  int n1=n/2, n2=n-n1;',
    '  vector<long long> left(a.begin(),a.begin()+n1);',
    '  vector<long long> right(a.begin()+n1,a.end());',
    '  vector<long long> leftSums, rightSums;',
    '  for(int mask=0;mask<(1<<n1);++mask){',
    '    long long sum=0;',
    '    for(int i=0;i<n1;++i) if(mask>>i&1) sum+=left[i];',
    '    leftSums.push_back(sum);',
    '  }',
    '  for(int mask=0;mask<(1<<n2);++mask){',
    '    long long sum=0;',
    '    for(int i=0;i<n2;++i) if(mask>>i&1) sum+=right[i];',
    '    rightSums.push_back(sum);',
    '  }',
    '  sort(rightSums.begin(),rightSums.end());',
    '  for(long long x:leftSums){',
    '    long long need=target-x;',
    '    if(binary_search(rightSums.begin(),rightSums.end(),need)) return true;',
    '  }',
    '  return false;',
    '}',
  ],
  'treap':[
    'pair<Node*,Node*> split(Node* t,int key){',
    '  if(!t) return {nullptr,nullptr};',
    '  if(t->key<key){',
    '    auto [a,b]=split(t->right,key);',
    '    t->right=a;',
    '    return {t,b};',
    '  }else{',
    '    auto [a,b]=split(t->left,key);',
    '    t->left=b;',
    '    return {a,t};',
    '  }',
    '}',
    'Node* merge(Node* a,Node* b){',
    '  if(!a||!b) return a?a:b;',
    '  if(a->priority<b->priority){ a->right=merge(a->right,b); return a; }',
    '  b->left=merge(a,b->left); return b;',
    '}',
  ],
  'expression-evaluation':[
    'long long evaluate(const vector<string>& tokens){',
    '  stack<long long> values;',
    '  stack<string> ops;',
    '  auto prec=[](const string& op){ return op=="+"||op=="-"?1:2; };',
    '  auto applyTop=[&](){',
    '    long long b=values.top(); values.pop();',
    '    long long a=values.top(); values.pop();',
    '    string op=ops.top(); ops.pop();',
    '    long long r=op=="+"?a+b:op=="-"?a-b:op=="*"?a*b:a/b;',
    '    values.push(r);',
    '  };',
    '  for(const string& t:tokens){',
    '    if(isdigit((unsigned char)t[0])) { values.push(stoll(t)); continue; }',
    '    if(t=="(") { ops.push(t); continue; }',
    '    if(t==")"){',
    '      while(!ops.empty() && ops.top()!="(") applyTop();',
    '      ops.pop();',
    '      continue;',
    '    }',
    '    while(!ops.empty() && ops.top()!="(" && prec(ops.top())>=prec(t)) applyTop();',
    '    ops.push(t);',
    '  }',
    '  while(!ops.empty()) applyTop();',
    '  return values.top();',
    '}',
  ],
  'shunting-yard':[
    'vector<string> toPostfix(const vector<string>& tokens) {',
    '  vector<string> output;',
    '  vector<string> ops;',
    '  auto precedence=[](const string& t){return t=="+"||t=="-"?1:2;};',
    '  for(const string& t:tokens){',
    '    if(isdigit((unsigned char)t[0])) { output.push_back(t); continue; }',
    '    if(t=="("){',
    '      ops.push_back("(");',
    '      continue;',
    '    }',
    '    if(t==")"){',
    '      while(!ops.empty() && ops.back()!="("){',
    '        output.push_back(ops.back());',
    '        ops.pop_back();',
    '      }',
    '      ops.pop_back();',
    '      continue;',
    '    }',
    '    while(!ops.empty() && ops.back()!="(" && precedence(ops.back())>=precedence(t)){',
    '      output.push_back(ops.back());',
    '      ops.pop_back();',
    '    }',
    '    ops.push_back(t);',
    '  }',
    '  while(!ops.empty()){',
    '    output.push_back(ops.back());',
    '    ops.pop_back();',
    '  }',
    '  return output;',
    '}',
  ],
  'fft':[
    'void fft(vector<complex<double>>& a){',
    '  int n=a.size();',
    '  if(n==1) return;',
    '  vector<complex<double>> even(n/2),odd(n/2);',
    '  for(int i=0;i<n/2;++i){',
    '    even[i]=a[2*i];',
    '    odd[i]=a[2*i+1];',
    '  }',
    '  fft(even);',
    '  fft(odd);',
    '  for(int k=0;k<n/2;++k){',
    '    complex<double> w=polar(1.0,2*PI*k/n);',
    '    a[k]=even[k]+w*odd[k];',
    '    a[k+n/2]=even[k]-w*odd[k];',
    '  }',
    '}',
  ],
  'ntt':[
    'void ntt4(array<int,4>& a){',
    '  int E0=(a[0]+a[2])%17, E1=(a[0]-a[2]+17)%17;',
    '  int O0=(a[1]+a[3])%17, O1=(a[1]-a[3]+17)%17;',
    '  int w=4;',
    '  a[0]=(E0+O0)%17;',
    '  a[2]=(E0-O0+17)%17;',
    '  a[1]=(E1+w*O1)%17;',
    '  a[3]=(E1-w*O1%17+17)%17;',
    '}',
  ],
}

const overrides:Record<string,TraceBuilder>={
  'meet-in-the-middle':lesson=>[
    eventFrame(lesson,'vector<long long> leftSums','a=[3,5,6,7], target=12','切成 Left=[3,5]、Right=[6,7]。每半只有 2²=4 個 subset。',{left:['3','5'],right:['6','7'],target:12,operation:'split input'}),
    eventFrame(lesson,'leftSums.push_back','枚舉 Left Sums','mask 00,01,10,11 對應 0,3,5,8。',{leftSums:['0','3','5','8'],operation:'enumerate left subsets'}),
    eventFrame(lesson,'rightSums.push_back','枚舉 Right Sums','得到 0,6,7,13。',{rightSums:['0','6','7','13'],operation:'enumerate right subsets'}),
    eventFrame(lesson,'sort(rightSums','排序右半','[0,6,7,13] 已是排序結果，可用 binary_search。',{rightSums:['0','6','7','13'],operation:'sort one half'}),
    eventFrame(lesson,'long long need=target-x','x=0：Need 12','Right 沒有 12；繼續。',{x:0,need:12,found:'false',operation:'probe complement'}),
    eventFrame(lesson,'binary_search','x=3：Need 9，也不存在','Right Sums 中找不到 9，因此這個 left sum 無法組成 target，繼續檢查下一個候選。',{x:3,need:9,found:'false',operation:'probe complement'}),
    eventFrame(lesson,'binary_search','x=5：Need 7，命中','Left subset {5} + Right subset {7}=12。',{x:5,need:7,found:'true',subset:['5','7'],operation:'find matching halves'}),
    eventFrame(lesson,'return true','回傳 True','把 O(2^n) 枚舉拆成兩個 O(2^(n/2)) 集合。',{result:'true',complexity:'O(2^(n/2) log 2^(n/2))',operation:'finish MITM'}),
  ].map((frame,step)=>({...frame,executionView:middleView(step)})),

  'treap':lesson=>[
    eventFrame(lesson,'split(Node* t','Treap：key 2(p30), 5(p10), 8(p20)','BST key 順序是 2<5<8，min-priority heap 讓 5(p10) 當 Root，左 2、右 8。',{tree:['root 5(p10)','left 2(p30)','right 8(p20)'],key:6,operation:'initialize treap split'}),
    eventFrame(lesson,'if(t->key<key)','Root key 5 < split key 6','5 應留在左半；只需要 split 它的右子樹 8。',{node:'5',decision:'go right',operation:'split root right'}),
    eventFrame(lesson,'split(t->right,key)','遞迴到 Node 8','8≥6，因此 8 應落在右半，接著 split 它的左子樹 null。',{node:'8',decision:'go left',operation:'recurse into 8'}),
    eventFrame(lesson,'if(!t)','Null Base 回傳 (null,null)','遞迴走到空子樹，表示這條 split 路徑已到達基底，可以開始回溯重接指標。',{result:['null','null'],operation:'split base'}),
    eventFrame(lesson,'t->left=b','回到 8：left 仍 Null','這層回傳 (null,8)。',{left:'null',right:'8(p20)',operation:'rewire right tree'}),
    eventFrame(lesson,'t->right=a','回到 5：right 改成 Null','這層回傳 (5-subtree,8)。左樹含 2、5；右樹含 8。',{left:['5(p10)','2(p30)'],right:['8(p20)'],operation:'rewire left tree'}),
    eventFrame(lesson,'return {t,b}','Split 完成','兩棵樹各自仍同時滿足 BST 與 priority heap 性質。',{result:['{2,5}','{8}'],operation:'finish split'}),
  ],


  'expression-evaluation':lesson=>[
    eventFrame(lesson,'stack<long long> values;','初始化兩個 Stack','Expression=3 + 4 * (2 - 1)。values=[] 保存數值，ops=[] 保存尚未結算的運算子。',{expression:'3 + 4 * (2 - 1)',values:[],ops:[],operation:'initialize parser'}),
    eventFrame(lesson,'values.push(stoll(t));','讀 3：Push 到 Values','數字可以立即進 values，不需要等待其他 token。',{token:'3',values:['3'],ops:[],operation:'push number 3'}),
    eventFrame(lesson,'ops.push(t);','讀 +：Push 到 Ops','ops 為空，沒有較高或同級 operator 需要先 reduce，因此 + 入 stack。',{token:'+',values:['3'],ops:['+'],operation:'push plus'}),
    eventFrame(lesson,'values.push(stoll(t));','讀 4：Push 到 Values','values=[3,4]。',{token:'4',values:['3','4'],ops:['+'],operation:'push number 4'}),
    eventFrame(lesson,'ops.push(t);','讀 *：優先序高於 +，直接 Push','precedence(+)<precedence(*)，不 pop +；ops=[+,*]。',{token:'*',values:['3','4'],ops:['+','*'],operation:'push multiply'}),
    eventFrame(lesson,'ops.push(t);','讀 (：建立 Barrier','左括號直接 push。它會阻止外層 *、+ 在括號內運算完成前被 reduce。',{token:'(',values:['3','4'],ops:['+','*','('],operation:'push left paren'}),
    eventFrame(lesson,'values.push(stoll(t));','讀 2：Push','values=[3,4,2]。',{token:'2',values:['3','4','2'],ops:['+','*','('],operation:'push number 2'}),
    eventFrame(lesson,'ops.push(t);','讀 -：因 Top 是 (，直接 Push','ops.top() 是左括號，所以 precedence while 不會跨過它；- 入 stack。',{token:'-',values:['3','4','2'],ops:['+','*','(','-'],operation:'push minus'}),
    eventFrame(lesson,'values.push(stoll(t));','讀 1：Push','values=[3,4,2,1]，接著遇到右括號。',{token:'1',values:['3','4','2','1'],ops:['+','*','(','-'],operation:'push number 1'}),
    eventFrame(lesson,'values.push(r);','右括號：Apply 2 - 1 = 1','applyTop pop b=1、a=2、op=-，算出 r=1，再 push 回 values；現在 values=[3,4,1]。',{a:2,b:1,op:'-',result:1,values:['3','4','1'],ops:['+','*','('],operation:'reduce inside parentheses'}),
    eventFrame(lesson,'ops.pop();','移除配對的左括號','top 已經是 (，所以括號內 reduction 停止；這一行只移除 barrier，本身不做算術。',{values:['3','4','1'],ops:['+','*'],operation:'discard left paren'}),
    eventFrame(lesson,'while(!ops.empty()) applyTop();','輸入結束：開始 Flush Ops','還有 *、+ 尚未結算；因為 stack LIFO，會先套用 * 再套用 +。',{values:['3','4','1'],ops:['+','*'],operation:'start final flush'}),
    eventFrame(lesson,'values.push(r);','先 Apply 4 * 1 = 4','applyTop 完成乘法，values 從 [3,4,1] 變 [3,4]，ops 只剩 +。',{a:4,b:1,op:'*',result:4,values:['3','4'],ops:['+'],operation:'reduce multiply'}),
    eventFrame(lesson,'values.push(r);','再 Apply 3 + 4 = 7','最後的 + 被結算，values 只剩唯一結果 7。',{a:3,b:4,op:'+',result:7,values:['7'],ops:[],operation:'reduce plus'}),
    eventFrame(lesson,'return values.top();','回傳 7','所有 token 都處理完成且 ops 已清空；values.top() 就是完整運算式的答案。',{result:7,operation:'return evaluated value'}),
  ].map((frame,step)=>({...frame,executionView:expressionView(step)})),

  'shunting-yard':lesson=>[
    eventFrame(lesson,'vector<string> output;','初始化 Output 與 Ops','Infix=3 + 4 * (2 - 1)。Output=[]；Ops=[]。',{tokens:['3','+','4','*','(','2','-','1',')'],output:[],ops:[],operation:'initialize'}),
    eventFrame(lesson,'output.push_back(t);','讀 3：Operand 直接輸出','後序式要求 operand 先出現，所以 3 直接放進 output。',{token:'3',output:['3'],ops:[],operation:'emit 3'}),
    eventFrame(lesson,'ops.push_back(t);','讀 +：Push Ops','沒有需要先輸出的 operator，因此 ops=[+]。',{token:'+',output:['3'],ops:['+'],operation:'push plus'}),
    eventFrame(lesson,'output.push_back(t);','讀 4：直接輸出','output=[3,4]。',{token:'4',output:['3','4'],ops:['+'],operation:'emit 4'}),
    eventFrame(lesson,'ops.push_back(t);','讀 *：+ 優先序較低，* 直接 Push','precedence(+)<precedence(*)，因此不 pop +；ops=[+,*]。',{token:'*',output:['3','4'],ops:['+','*'],operation:'push multiply'}),
    eventFrame(lesson,'if(t=="(")','讀 (：Push Barrier','左括號只負責限制 operator pop 範圍，不會出現在 postfix output。',{token:'(',output:['3','4'],ops:['+','*','('],operation:'push left paren'},{codeAnchor:'ops.push_back(t);'}),
    eventFrame(lesson,'output.push_back(t);','讀 2：直接輸出','output=[3,4,2]。',{token:'2',output:['3','4','2'],ops:['+','*','('],operation:'emit 2'}),
    eventFrame(lesson,'ops.push_back(t);','讀 -：Top 是 (，所以直接 Push','左括號阻止外層 *、+ 被 pop；ops=[+,*,(,-]。',{token:'-',output:['3','4','2'],ops:['+','*','(','-'],operation:'push minus'}),
    eventFrame(lesson,'output.push_back(t);','讀 1：直接輸出','output=[3,4,2,1]。',{token:'1',output:['3','4','2','1'],ops:['+','*','(','-'],operation:'emit 1'}),
    eventFrame(lesson,'output.push_back(ops.back());','讀 )：先把 - 移到 Output','右括號要求輸出直到左括號；因此 - 被 append 到 output，形成 [3,4,2,1,-]。',{token:')',moved:'-',output:['3','4','2','1','-'],ops:['+','*','('],operation:'flush inside parens'}),
    eventFrame(lesson,'ops.pop_back();','丟棄左括號本身','top 現在是 (；它只負責 grouping，不屬於 postfix，所以直接 pop 而不輸出。',{output:['3','4','2','1','-'],ops:['+','*'],operation:'discard left paren'},{sourceOccurrence:1}),
    eventFrame(lesson,'output.push_back(ops.back());','輸入結束：先 Flush *','stack top 是 *，先輸出得到 [3,4,2,1,-,*]。',{moved:'*',output:['3','4','2','1','-','*'],ops:['+'],operation:'flush multiply'},{sourceOccurrence:2}),
    eventFrame(lesson,'output.push_back(ops.back());','再 Flush +','最後把 + 輸出，得到完整 postfix [3,4,2,1,-,*,+]。',{moved:'+',output:['3','4','2','1','-','*','+'],ops:[],operation:'flush plus'},{sourceOccurrence:2}),
    eventFrame(lesson,'return output;','Postfix 完成','結果 3 4 2 1 - * + 對應 3 + 4 * (2 - 1)。括號消失，但原優先序與 grouping 已寫入 token 順序。',{result:'3 4 2 1 - * +',operation:'return postfix'}),
  ].map((frame,step)=>({...frame,executionView:shuntingView(step)})),

  'fft':lesson=>[
    eventFrame(lesson,'fft(vector','輸入係數 [1,2,3,4]','n=4。FFT 先把偶數 index 與奇數 index 分成兩個 n/2 子問題。',{input:['1','2','3','4'],n:4,operation:'initialize FFT'}),
    eventFrame(lesson,'even[i]=a[2*i];','收集 Even = [1,3]','i=0、1 時同一 assignment 分別讀 a[0]、a[2]。',{even:['1','3'],operation:'collect even coefficients'}),
    eventFrame(lesson,'odd[i]=a[2*i+1];','收集 Odd = [2,4]','另一行分別讀 a[1]、a[3]。',{odd:['2','4'],operation:'collect odd coefficients'}),
    eventFrame(lesson,'fft(even);','先遞迴算 Even DFT','長度 2 的 [1,3] 變成 E=[4,-2]。',{input:['1','3'],E:['4','-2'],operation:'solve even transform'}),
    eventFrame(lesson,'fft(odd);','再遞迴算 Odd DFT','長度 2 的 [2,4] 變成 O=[6,-2]。',{input:['2','4'],O:['6','-2'],operation:'solve odd transform'}),
    eventFrame(lesson,'complex<double> w=polar','k=0：Twiddle w=1','準備第一個 butterfly。',{k:0,w:'1',operation:'compute twiddle k0'}),
    eventFrame(lesson,'a[k]=even[k]+w*odd[k];','寫 a[0]=10','4+1·6=10。',{k:0,result:10,operation:'write upper butterfly k0'}),
    eventFrame(lesson,'a[k+n/2]=even[k]-w*odd[k];','寫 a[2]=-2','4-1·6=-2。',{k:0,result:-2,operation:'write lower butterfly k0'}),
    eventFrame(lesson,'complex<double> w=polar','k=1：Twiddle w=i','第二個 butterfly 使用 ω₄=i。',{k:1,w:'i',operation:'compute twiddle k1'}),
    eventFrame(lesson,'a[k]=even[k]+w*odd[k];','寫 a[1]=-2-2i','-2+i·(-2)=-2-2i。',{k:1,result:'-2-2i',operation:'write upper butterfly k1'}),
    eventFrame(lesson,'a[k+n/2]=even[k]-w*odd[k];','寫 a[3]=-2+2i','-2-i·(-2)=-2+2i。',{k:1,result:'-2+2i',operation:'write lower butterfly k1'}),
    eventFrame(lesson,'a[k+n/2]=even[k]-w*odd[k];','DFT 完成','最終 [10,-2-2i,-2,-2+2i]。',{result:['10','-2-2i','-2','-2+2i'],operation:'finish FFT'}),
  ]

  'ntt':lesson=>[
    eventFrame(lesson,'ntt4','在 mod 17 做長度 4 NTT，輸入 [1,2,3,4]','4 是 mod17 的四次原根：4²=16=-1、4⁴=1。',{mod:17,root:4,input:['1','2','3','4'],operation:'initialize NTT'}),
    eventFrame(lesson,'E0=(a[0]+a[2])','偶數位置 1,3 的長度 2 Transform','E0=1+3=4；E1=1-3=-2≡15。',{E0:4,E1:15,operation:'transform even half'}),
    eventFrame(lesson,'O0=(a[1]+a[3])','奇數位置 2,4','O0=6；O1=2-4=-2≡15。',{O0:6,O1:15,operation:'transform odd half'}),
    eventFrame(lesson,'a[0]=(E0+O0)','k=0 Butterfly','a0=4+6=10；a2=4-6=-2≡15。',{a0:10,a2:15,operation:'butterfly k0'}),
    eventFrame(lesson,'a[1]=(E1+w*O1)','k=1 使用 w=4','w*O1=4×15=60≡9；a1=15+9=24≡7。',{wO1:9,a1:7,operation:'butterfly k1 plus'}),
    eventFrame(lesson,'a[3]=(E1-w*O1','另一半 a3=15-9=6','所有計算都在有限域中精確進行。',{a3:6,operation:'butterfly k1 minus'}),
    eventFrame(lesson,'a[3]=(E1-w*O1','NTT 結果 [10,7,15,6]','不含浮點誤差；inverse 時改用逆根並乘 n^-1。',{result:['10','7','15','6'],operation:'finish NTT'}),
  ],
}

export const applyS2MiscOverride=(lesson:AlgorithmLesson):AlgorithmLesson=>{
  const build=overrides[lesson.id]
  if(!build) return lesson
  const coded={...lesson,code:codeOverrides[lesson.id]}
  return {...coded,frames:build(coded),traceMode:'execution',animationVersion:2}
}

export const s2MiscOverrideIds=Object.freeze(Object.keys(overrides))
